### ISSUE TITLE
视频封面能放到视频本身目录吗

### ISSUE THREAD

**Issue by jjss520** [hitchao/Jvedio#1]
文件名和视频名称一样

**Comment by hitchao** [comment]
只能放在Pic目录下各分类的文件夹




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jjss520"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月3日(星期五) 下午2:19
收件人:&nbsp;"hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hitchao/Javedio-2.0] 视频封面能放到视频本身目录吗 (#1)




文件名和视频名称一样

**Comment by hitchao** [comment]
可以
