### ISSUE TITLE
javlibrary刮削失败

### ISSUE THREAD

**Issue by Jinghaoma** [hitchao/Jvedio#103]
# 描述：
使用https://www.javlibrary.com/cn/ 这个网址好像无法刮削了，一部分日志如下，感觉像被屏蔽了。
感觉lib对出演者的名字写的比较全，所以挺希望能从这里爬取数据的，十分感谢。

详细说明前因后果、操作步骤。

# 日志文件：
【2021/7/19 13:30:40】=> 服务器地址：https://www.javlibrary.com/cn/， 原因：远程服务器返回错误: (403) 已禁止。
【2021/7/19 13:30:44】=> 服务器地址：https://www.javlibrary.com/cn/， 原因：远程服务器返回错误: (403) 已禁止。
【2021/7/19 13:30:45】=> 服务器地址：https://www.javlibrary.com/cn/， 原因：远程服务器返回错误: (403) 已禁止。
【2021/7/19 13:37:14】=> 服务器地址：https://javlib.com/vl_searchbyid.php?keyword=SSIS-115， 原因：远程服务器返回错误: (404) 未找到。
【2021/7/19 13:37:15】=> 服务器地址：https://javlib.com/vl_searchbyid.php?keyword=XRW-502， 原因：远程服务器返回错误: (404) 未找到。
【2021/7/19 13:37:15】=> 服务器地址：https://javlib.com/vl_searchbyid.php?keyword=YMDS-030， 原因：远程服务器返回错误: (404) 未找到。
【2021/7/19 13:40:47】=> 服务器地址：https://www.javlibrary.com， 原因：远程服务器返回错误: (403) 已禁止。

**Comment by yizsy928** [comment]
DB 获取 cookie 但状态还是红叉咋回事
