### ISSUE TITLE
软件同步或者扫描经常卡死崩溃

### ISSUE THREAD

**Issue by adddc7** [hitchao/Jvedio#104]
# 由于一些个人原因，Jvedio 暂时维护，目前最新版 [4.6.0.0]( https://github.com/hitchao/Jvedio/releases/tag/Jvedio4.6.0.0)，或下载 [其他版本](https://github.com/hitchao/Jvedio/releases)

## 你仍然可以提交的问题，但可能在半年后才能解决，可以下载 [其他版本](https://github.com/hitchao/Jvedio/releases)

# 反馈
1、软件经常不定时同步卡死、崩溃，强制结束无法关闭 崩溃时把所有软件或者浏览器一起卡死导致空白无法关闭，只能强制重启后，导致软件无法启动 只能删除后换盘或者文件夹重新安装和同步资料（占用内存高）
2、特别智能分类同步时间过长经常90%开始无法动弹和扫描硬盘（有几率卡死）
3、同步信息新增网站地址保存后，重新打开显示同步信息 网址全消失或者缺少部分网址
4、右边同步显示信息下载失败条框能否设定3S后自动消失，一个个点关闭真的难繁琐
5、右边的快速搜索栏，能否调一下显眼的填充颜色或者做一个带颜色框架 这样容易分辨出来对应的字母
6、部分影片修改了图片或者文字内容资料编辑，一旦按了同步信息就会强制覆盖已修改的影片资料（能否制作锁定资料编辑，这样无法同步覆盖 需要同步时候就解除锁定）
- 出现问题的版本：（如4.5.0.0）
Jvedio4.6.1.1
- 电脑系统：（如 win 10）
Windows 10 专业版
# 描述：

详细说明前因后果、操作步骤。

# 日志文件：
请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/Introduction_3)

**Comment by hitchao** [comment]
5.0 基本已修复
