### ISSUE TITLE
用了一小段时间，挺好用的，刮削比avdc好，不用挂梯子，页面显示比kodi更好。有些小建议

### ISSUE THREAD

**Issue by xiaolismallpear** [hitchao/Jvedio#110]
# 由于一些个人原因，Jvedio 暂时维护，目前最新版 [4.6.0.0]( https://github.com/hitchao/Jvedio/releases/tag/Jvedio4.6.0.0)，或下载 [其他版本](https://github.com/hitchao/Jvedio/releases)

## 你仍然可以提交的问题，但可能在半年后才能解决，可以下载 [其他版本](https://github.com/hitchao/Jvedio/releases)

# 反馈

1.能否支持关联已刮削完成的电影，我用tinyMediaManager刮削的本地电影，无法扫描至影库，貌似不能读取影片下nfo和海报图，显示已扫描完成，刷新却没有。
2.本地扫描执行完成后，按停止按钮会闪退，试了很多次 都是这样。
3、能否兼容其他刮削服务器，豆瓣、themoviedb、rarbg等，不用自带，可让用户自行设置，目前好像只有bus能保存成功。
4、显示框内显示的顺序是文件名、时间、星级、副标题，是固定的，可否让用户设置显示框内的内容。
5、同步信息按钮可否做成二级菜单，同步海报和同步剧照，同步海报可全选同步，剧照貌似只能一个一个点开同步。
6、图片保存路径可否让用户选择，设置在一个目录或者电影文件的目录。
以上，毫无恶意，纯使用心得，希望这款软件能成为全面的影片管理工具，希望作者越来越好。

**Comment by hitchao** [comment]
146都已经实现了，在设置里可以调整。
其他的后续会修复。
谢谢你的支持和鼓励！
