### ISSUE TITLE
这个软件用了半年多了，越用越顺手，但也发现了几个小小的问题

### ISSUE THREAD

**Issue by cjchnws3** [hitchao/Jvedio#112]
- 出现问题的版本：4.6.1.1

- 电脑系统：win 10 LTSC X64

# 描述：
主要是关于演员方面的。
1.记得在之前的版本的时候，点击“加载该演员其他作品”时，是可以加载出作品列表的。但不知道从哪一版本开始，点击加载，会出现“仅支持BUS”的提示。但刮削服务器设置是正确的，用的是javbus，平时也能刮削下来。

2.部分演员的信息无法刮削。大部分情况都是没问题的，但如果遇到信息不全，只有头像的演员时，就会直接跳过。例如：琴石ゆめる 

3.另外如果选择全部演员，进行刮削演员信息，由于有无法刮削的对象，将其他能刮削的信息全都下载好后，进度条就会一直加载。

4.在主界面，右键点击单个影片，选择“立即同步”后，会刮削下来海报和摘要，但是却没有同步预览图等。需要点进影片信息界面，再右键“立即同步”才会下载预览图。

其实都是小问题哈，这个软件做的挺棒的，希望作者不要放弃更新维护。

**Comment by hitchao** [comment]
谢谢，后面更新我会考虑的。

**Comment by zhi2103** [comment]
可以考虑选择多个文件后，一次性添加到播放器列表里吗？貌似现在的软件是不支持这样的功能，每次播放只能单个点击相应的文件，这样降低了连续播放的流畅性

**Comment by hitchao** [comment]
5.0 基本已修复
