### ISSUE TITLE
关于3.0版本的一些微小建议

### ISSUE THREAD

**Issue by fanza1** [hitchao/Jvedio#12]
图书馆可能比较难爬，建议可以换成爬取dmm的信息，可能会容易实现一点。另外，图书馆的图片都是链接的dmm的图库，而且图像的命名是有规律的，而且dmm图库在中国没有被墙也无需日本ip访问，可以靠模板自动生成链接爬取。

BTW像这种本地JAV管理软件少之又少，希望大佬能坚持下去，之前论坛里看到就赞助了一杯coffee，一些微小的支持，毕竟个人开发者纯属靠爱发电，祝生活愉快！

**Comment by hitchao** [comment]
没问题~ 3.0准备上线了------------------ 原始邮件 ------------------
发件人: "fanza1"<notifications@github.com>
发送时间: 2020年4月16日(星期四) 晚上8:10
收件人: "hitchao/Jvedio"<Jvedio@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [hitchao/Jvedio] 关于3.0版本的一些微小建议 (#12)




 
图书馆可能比较难爬，建议可以换成爬取dmm的信息，可能会容易实现一点。另外，图书馆的图片都是链接的dmm的图库，而且图像的命名是有规律的，而且dmm图库在中国没有被墙也无需日本ip访问，可以靠模板自动生成链接爬取。
 
BTW像这种本地JAV管理软&#x4EF6;少之又少，希望大佬能坚持下去，之前论坛里看到就赞助了一杯coffee，一些微小的支持，毕竟个人开发者纯属靠爱发电，祝生活愉快！
 
&mdash;
