### ISSUE TITLE
真的好用，感谢！有个小问题

### ISSUE THREAD

**Issue by vjtso** [hitchao/Jvedio#124]
# 反馈
识别vr影片有两个问题:
1、一个番号经常是好几个文件，比如sivr00137.part1.mp4，然后一直到part4总共4个文件，扫描的时候log里会报重复。这个还好，不是太影响。
2、不知道为啥vr影片下载下来文件名经常是五个数字，前面多两个零，比如kavr00132.mp4，然后会被识别成KAVR-00132导致同步时候找不到。每次都要手动修改，非常麻烦，而且必须要改文件名，不然下次扫描又进来了。

- 出现问题的版本：4.6.1.1

- 电脑系统：win 10

**Comment by hitchao** [comment]
收到
