### ISSUE TITLE
视频扫描时能自动添加符合识别码的.htm文件为影片文件

### ISSUE THREAD

**Issue by ss20226** [hitchao/Jvedio#126]
# 反馈

- 出现问题的版本：（如4.6.1.1）

- 电脑系统：（如 win 7）

# 描述：

如题，特殊需求，希望能增加这个功能

# 日志文件：

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/Introduction_3)

**Comment by hitchao** [comment]
新版本将添加支持
