### ISSUE TITLE
关于多版本影片的添加问题

### ISSUE THREAD

**Issue by shirogane5687** [hitchao/Jvedio#128]
感谢作者！软件潜力很大！加油加油。
就是有一个功能上的问题，
我现在有些影片保存了不同大小多版本，是用 片名[影片大小].mp4 这种命名格式保存的，
这种情况应该怎么添加呢？能不能添加一个适应添加多版本影片的功能。
我也考虑过用尝试用分段影片的方式去添加，但是分段影片命名只支持-cd1或者fhd1这种，因为现在影片库很大，如果让我重新再命名，工程量太大了，能不能扩大命名支持的规则，最好能支持 片名[影片大小].mp4 这种的。
再次感谢！
最后再问一下有没有交流tg群什么的，感觉目前教程还比较简略，如果是从一开始就发现了Jvedio，直接使用的话可能还好点，如果已有影片库，想去适配Jvedio的场合，就会有很多问题不知道该怎么办了。

**Comment by hitchao** [comment]
tg群搜jvedio就有，你这种多版本的我想jvedio5.0应该能支持

**Comment by shirogane5687** [comment]
> tg群搜jvedio就有，你这种多版本的我想jvedio5.0应该能支持

好的，感谢！

**Comment by hitchao** [comment]
使用影片关联功能吧，5.0 里面的
