### ISSUE TITLE
部分视频无法导入

### ISSUE THREAD

**Issue by ContinueStudio** [hitchao/Jvedio#129]
# 反馈

- 出现问题的版本：4.6.1.1

- 电脑系统： win 10

# 描述：

查看了之前的提问，说是视频没有视频码就无法识别。
但是作为一个小白，几千部电影如果手动去添加视频码是否太恐怖了。。
请问现在这个问题有更好的解决方法了吗？

**Comment by hitchao** [comment]
下一个大版本就支持了

**Comment by ContinueStudio** [comment]
> 下一个大版本就支持了

下个大版本大概什么时候能用上呢？顺便报一个BUG，在把GIF缩略图的尺寸调到1280的时候，再生成GIF缩略图，软件就一直闪退。

**Comment by hitchao** [comment]
估计3月份吧
