### ISSUE TITLE
咨询下3.0版的问题

### ISSUE THREAD

**Issue by ghost** [hitchao/Jvedio#13]
导入以后，封面的左上角有高清视频的标签。
请问下可以关闭吗？

**Comment by RobertChou** [comment]
有同感，基本都是高清的

**Comment by hitchao** [comment]
最新版已经修复

**Comment by RobertChou** [comment]
最新版还没放出下载吗？

**Comment by RobertChou** [comment]
看了3.1版，左上角还是有高清的标志

**Comment by hitchao** [comment]
可自行取消------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;RobertChou&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月24日(星期天) 晚上10:26
收件人:&nbsp;&quot;hitchao/Jvedio&quot;<Jvedio@noreply.github.com&gt;;
抄送:&nbsp;&quot;hitchao&quot;<2415923016@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [hitchao/Jvedio] 咨询下3.0版的问题 (#13)

**Comment by fanza1** [comment]
在设置->显示 中取消“标记”即可

**Comment by RobertChou** [comment]
已经摸索出来了，作者可以设置一个选项是按照演员排序吗？

**Comment by fanza1** [comment]
> 已经摸索出来了，作者可以设置一个选项是按照演员排序吗？

感觉是个鸡肋功能
