### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by nfsking2** [hitchao/Jvedio#133]
# 反馈

用了一周左右，很不错的软件。给大佬赞一个。

有几个功能建议，望酌情采纳：

1. 希望增加演员头像及信息的批量获取功能。

2. 设置里面的信息源网站可以多选，但似乎只有其中一个能起作用。希望可以支持根据源网站顺序作为优先级，当某个源无法获取到影片信息时，可以自动尝试下一个源。目前来看DB信息最全，但有部分影片信息依然缺失，DMM没有FC2和蚊香社的信息，BUS目前暂时无法使用，同步时软件100%闪退，MOO无法正常获取任何信息。

3. 可以将多个演员名字做关联。毕竟演员跳到另一个事务所或者厂牌后经常艺名也会发生变化，有些演员无法用新艺名获取到信息，而老艺名又无法正确被软件获取。另一种情况是从DB获取到的演员名字，部分并非日文汉字而是繁体字，比如“亜”和“亞”，从而导致部分演员的信息无法正确从BUS获取。如果能将两个或者多个艺名做关联，无法用第一个名字获取信息时，则可以跳到另一个被关联的名字。如果这个功能不好实现，是否可以在演员详细信息界面修改演员名字，并自动更新到对应的影片信息当中？

4. 支持手动指定除DB外的其他网站的影片链接。

5. 针对单个影片获取信息以及演员信息的获取，建议也增加当前软件正在执行的操作。有时候获取速度比较慢，但软件中没有任何提示，会让人误认为无法获取到信息。

6. 建议在列表和影片详情界面的识别码旁，增加VR影片的标识。

7. 建议过滤掉男演员姓名。目前为了实现这个目的，我作为一个非程序员，只能用Navicat这类软件打开数据库文件，再自学SQL语句把能查询到的男演员名字从movie表的actor列中删除。但似乎SQLite语句不支持删除多个不同字串符，用嵌套REPLACE语句的方法可以变通实现，但字串数量超过20个时Navicat这类软件会吃满至少64GB内存，因此目前我只能把男演员名字分成20个一组，多次执行REPLACE函数来删掉这些名字（当然还是比在软件里手动编辑影片信息快很多）。如果这个功能不好实现，不知道是否有其他方法可以曲线救国？

8. 似乎软件即便是在设置了“启动时扫描以下目录”后，依然无法自动扫描指定目录下新增的影片？毕竟片库内的影片是不断增加的，每次都需要手动把新片拖进软件来更新片库有点不方便。不知道是不是可以增加一个目录监控功能，自动扫描和获取新增影片的信息？

**Comment by hitchao** [comment]
可以，后面会根据具体情况改进
