### ISSUE TITLE
同步闪退问题 

### ISSUE THREAD

**Issue by 776725893** [hitchao/Jvedio#134]
# 反馈

- 出现问题的版本：（如4.5.0.0）

- 电脑系统：（如 win 10）

# 描述：

详细说明前因后果、操作步骤。

# 日志文件：

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/Introduction_3)

**Comment by 776725893** [comment]
电脑系统：win11，
点击同步后2~3s就闪退

**Comment by hitchao** [comment]
部分影片会闪退，同步单个影片可以找到

**Comment by 776725893** [comment]
> 部分影片会闪退，同步单个影片可以找到

单个的我也试了，都不行；再进去的话标题等是同步出来了 除了图片

**Comment by Chinreimei** [comment]
同闪退
win11
4.6.1.1版本
同步到8%左右就闪退 使用上一个版本也存在同样的情况 单个也会闪退
