### ISSUE TITLE
Gif页面显示模式下闪退等问题

### ISSUE THREAD

**Issue by Madaerpao** [hitchao/Jvedio#135]
# 反馈

- 出现问题的版本：lastest version

- 电脑系统：win11

# 描述：

- 1.将页面显示由“海报”改为“GIF”时，页面刷新加载时间较久（有时20秒左右）。

- 2.在GIF显示模式下，页面显示**影片数量50时，切换页面概率闪退**，显示影片数量100时，切换页面会导致**必然闪退**，暂无例外。

- 3.Win11系统下，窗口最大化、最小化，有明显的掉帧延迟，点击时能感受到明显的软件卡顿。

- 4.批处理问题：任务数量获取不正确，某些片会被忽略。

- 5.同步问题：同步预览图经常出现“地区或国家未上架……”，必须全部清空信息后更换网址才能从其他网址同步（如，bus出现上述问题无法同步，需要清空信息后指定DB网址进行同步），能否增加同步网址失败自动切换功能或手动切换功能？

# 日志文件：

无

**Comment by hitchao** [comment]
gif 暂时先搁置
