### ISSUE TITLE
需求建议

### ISSUE THREAD

**Issue by lylunula** [hitchao/Jvedio#136]
首先感谢作者提供了这么优秀的软件，我用的很顺手，是我理想中管理影片的好工具。但有些建议希望能让软件越做越好：

1. 最重要的是希望能适配目前的刮削格式：其实很多影片内容已经用其他刮削器处理过了，基本上都是视频文件+NFO+图片在同一个文件夹里面用同样的文件名，能不能在导入的时候默认就读取，而不是要分3次导入，还要把图片复制到单独的文件夹里面。这种做法基本上是plex、emby、jellyfin的主流做法，可以直接follow这样的格式来

2. 演员信息优化：
- 管理时可以自己添加更多自定义字段，便于自己评价和管理。这样也可以多维度打分和记录
- 加上评分分级
- 可以多附上几张照片，这样可以有多个角度截图记录
- 可以分组管理，或者选择tag也行

2. 列表显示能显示对应的演员名，目前只有文件名；另外希望支持对于影片添加备注

3. 演员信息抓取好像抓取了很多演员，是正常的么？

4. 清单可以创建智能清单，有点像itunes，符合某些筛选条件即可加入到该清单中

6. bug：导入NFO同时复制图片后，遇到.ts/文件夹就会卡死

7. bug：同时同步700+影片，就会出问题，是不是性能处理上没有压测这种case？

**Comment by hitchao** [comment]
收到，感谢提供建议！
