### ISSUE TITLE
Jvedio启动后机械硬盘会响动，产生噪音。

### ISSUE THREAD

**Issue by YaoYouGuan** [hitchao/Jvedio#141]
# 反馈

- 出现问题的版本：4.6.1.1

- 电脑系统：win7

# 描述：

Jvedio启动的时候，电脑中的机械存储盘会响动一会儿，大概就几秒钟。每次都启动都这样 还挺吵的。
TG群内交流了解到是启动时候会判断是否可播放，就会去访问文件夹。然后硬盘读取，产生噪音。
就想要针对这个现象做一个优化。

**Comment by elwinYe** [comment]
这个你要怎么优化？读盘时针头划碟的声音还能物理消除？

**Comment by hitchao** [comment]
磁盘读取主要是有几个地方
1。判断是否可播放。这个可以做一个缓存，记录先前文件存在状态，用户可以自行更新缓存，减少磁盘读取次数
2。启动时扫描。预先判断一下文件夹大小文件数量是否变动
3。图片的读取。提示用户最好将图片存在固态硬盘，可以复制一些常读取的图片到c盘（固态硬盘），提高图片加载速度，减少磁盘读取
4。数据库的读取。新版本中将支持sqlite,mysql,postgresql等数据库，减少硬盘的读取

**Comment by YaoYouGuan** [comment]
Nice！看了第3点，我才想起我现在的Jevdio和作品大全，是放在机械硬盘的。那我回去将Jvedio安装目录放在固态盘，这样至少在访问图片资料时没有噪音了。
