### ISSUE TITLE
Linux端

### ISSUE THREAD

**Issue by milkbrother666** [hitchao/Jvedio#142]
请问后续会有推出Linux服务端吗？还是说需要自行编译？

**Comment by hitchao** [comment]
半年后可能会开始做，关于linux端这方面你有什么想法吗

**Comment by milkbrother666** [comment]
> 半年后可能会开始做，关于linux端这方面你有什么想法吗

主要是又想打造一个家庭影院，一直没有在市场上找到合适的开源产品。
关于软件本身的功能上可能需要后续慢慢开发及完善。

但是对于Linux端来说，建议推出的服务端采用无格式二进制部署，不建议采用软件包安装。这样做有几个好处。
对开发者来讲：
- 可以减少对操作系统选择的局限
- 降低发布周期及测试成本

对使用者来讲：
- 方便更加灵活的部署

**Comment by hitchao** [comment]
> > 半年后可能会开始做，关于linux端这方面你有什么想法吗
> 
> 主要是又想打造一个家庭影院，一直没有在市场上找到合适的开源产品。 关于软件本身的功能上可能需要后续慢慢开发及完善。
> 
> 但是对于Linux端来说，建议推出的服务端采用无格式二进制部署，不建议采用软件包安装。这样做有几个好处。 对开发者来讲：
> 
> * 可以减少对操作系统选择的局限
> * 降低发布周期及测试成本
> 
> 对使用者来讲：
> 
> * 方便更加灵活的部署

那关于开发的语言和框架，你推荐采用什么

**Comment by milkbrother666** [comment]
> > > 半年后可能会开始做，关于linux端这方面你有什么想法吗
> > 
> > 
> > 主要是又想打造一个家庭影院，一直没有在市场上找到合适的开源产品。 关于软件本身的功能上可能需要后续慢慢开发及完善。
> > 但是对于Linux端来说，建议推出的服务端采用无格式二进制部署，不建议采用软件包安装。这样做有几个好处。 对开发者来讲：
> > 
> > * 可以减少对操作系统选择的局限
> > * 降低发布周期及测试成本
> > 
> > 对使用者来讲：
> > 
> > * 方便更加灵活的部署
> 
> 那关于开发的语言和框架，你推荐采用什么

对于开发这方面我并不是很懂，但是从性能和可移植性方面来讲无疑是C/C++/Go/Java这些语言的，但是从开发难度来讲Python也是不错的，但是Python的运行速度不知道能不能达到服务端的需求

**Comment by xermao** [comment]
现在C#不是可以跨平台了嘛，继续用C#呗

**Comment by hitchao** [comment]
感觉c#跨平台有点拉胯，文档也不是很多，准备用java写一下linux和安卓的，后面有时间补一个C++版本的

**Comment by milkbrother666** [comment]
> 现在C#不是可以跨平台了嘛，继续用C#呗

需要考虑一个性能问题，不仅仅是跨平台问题

**Comment by xermao** [comment]
> > 现在C#不是可以跨平台了嘛，继续用C#呗
> 
> 需要考虑一个性能问题，不仅仅是跨平台问题

又不是计算密集型程序，语言的那点性能差异体现不出来的。除非是他拿C#写解码器。

**Comment by hitchao** [comment]
性能倒不是啥大问题，目前jv卡顿是因为一些细节处理不好，用java或者C++的原因主要是C#跨平台文档太少，而且也不是很成熟，与其跟微软耗着，不如用其他语言的优势弥补

**Comment by xermao** [comment]
能不用C++就尽量不用吧，一个是写起来慢，另一个是真出BUG了，也不好找。

**Comment by spartawhy117** [comment]
> 性能倒不是啥大问题，目前jv卡顿是因为一些细节处理不好，用java或者C++的原因主要是C#跨平台文档太少，而且也不是很成熟，与其跟微软耗着，不如用其他语言的优势弥补

建议别用裸c++，Qt 都比纯c++省事情。图效率的话，服务端用py就行了，开发效率和查bug效率高很多
