### ISSUE TITLE
关于读取现有nfo文件的问题

### ISSUE THREAD

**Issue by laoyu1986** [hitchao/Jvedio#143]
# 反馈
用其他刮削器刮削后，然后用Jvedio管理。读取  nfo文件后，“系列”类目混乱。
对比发现：Jvedio刮削后nfo文件中与“系列”相关的内容归类在tag字段里，而其他刮削器刮削写入的nfo文件中与“系列”相关的是在series/set字段里面，所以就导致在Jvedio在读取“系列”内容时，实际读取的是其他软件生成nfo文件里的tag字段的内容。希望作者是不是可以在下个版本修改一下？最好能用set字段，应为tag的话可能做“标签”理解更确切。谢谢

- 出现问题的版本：（如4.5.0.0）

- 电脑系统：（如 win 10）

# 描述：

详细说明前因后果、操作步骤。

# 日志文件：

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/Introduction_3)

**Comment by hitchao** [comment]
可以，我看一下

**Comment by hitchao** [comment]
已修复
