### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by elwinYe** [hitchao/Jvedio#145]
软件版本：v4.6.1.1
OS： win10 x64

用了挺长一段时间，感觉各个方面都挺不错，对于仓鼠党而言，请问在未来的版本中是否可以考虑加入 同步信息时 不同步 影片名称这个选项呢？ 毕竟在下载到本地后，经常会将其进行重命名为中文名称的操作以方面选择预览。
例如：文件名称： ABC-001 葫芦娃.mp4的文件同步信息后 在 软件库中的名称就会被修改为对应番号的日文名称。

希望作者不要放弃维护，加油！

**Comment by hitchao** [comment]
影片名称肯定会同步，但是可以不显示名称而是显示文件名
