### ISSUE TITLE
图片缓存位置问题

### ISSUE THREAD

**Issue by JadeButterfly** [hitchao/Jvedio#149]
# 反馈
能不能设置在影片位置扫描海报缩略图等图片以免额外挪动文件，以及自定义图片名称格式

**Comment by hitchao** [comment]
可以，下一版本加上

**Comment by wujie985432** [comment]
> 可以，下一版本加上

下一版几号出呀，等了快一年了

**Comment by hitchao** [comment]
最快可能月底

**Comment by hitchao** [comment]
> # 反馈
> 能不能设置在影片位置扫描海报缩略图等图片以免额外挪动文件，以及自定义图片名称格式

最近测了下，自定义图片格式比较麻烦，不考虑加入了
