### ISSUE TITLE
关于3.0版本主程序运行的问题

### ISSUE THREAD

**Issue by EvenYuan** [hitchao/Jvedio#15]
之前3月份和5月份的版本我都用过，但都出现同一个问题：
一开始很正常，但用了没多久以后，点击主程序就只看到程序在任务栏出现，主程序窗口、UI显示不出来，鼠标指在任务栏对应图标上显示不了窗口；即便电脑重启以后，也是出现同样的问题。虽然2.0能用，但还是比较喜欢3.0版本这个UI，希望作者能试试能否提供该问题的解决方法和思路？
最后感谢作者从1.0到3.0的不懈维护，为众多视频仓鼠提供了极大的便利，希望该项目日益完善~

**Comment by hitchao** [comment]
触发条件确实是 最小化时关闭程序
解决办法：删除 C:\Users\chao\AppData\Local\Jvedio 下所有文件

**Comment by ftdtyzst** [comment]
任务管理器里左键点选jvedio的 > 
再右键点选jvedio 选最大化 就出来了
然后在程序边缘拉小程序就行 自己摸索出来的办法

**Comment by ftdtyzst** [comment]
大大不再开发这个软件了吗？

**Comment by hitchao** [comment]
4.0 准备上线了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hitchao/Jvedio"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月15日(星期二) 凌晨0:37
收件人:&nbsp;"hitchao/Jvedio"<Jvedio@noreply.github.com&gt;;
抄送:&nbsp;"chao"<2415923016@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [hitchao/Jvedio] 关于3.0版本主程序运行的问题 (#15)





 
大大不再开发这个软件了吗？
