### ISSUE TITLE
db这个网站的cookie问题

### ISSUE THREAD

**Issue by clggwater** [hitchao/Jvedio#150]
用的最新版本，之前一直用的bus，但是内容没有javdb全，按照教程，我提取了cookie，但是提交之后全部不通过，试了很多次，这个网站是不是特殊？我提交的内容是图中，theme开始，3D%3D结束，还是我的内容格式有问题？
![image](https://user-images.githubusercontent.com/23073985/158351336-c1dc8b1f-bc56-4d5d-826e-2611b3c88ea9.png)

**Comment by hitchao** [comment]
db我自己的也不行，有cloudfare反扒

**Comment by clggwater** [comment]
实测，只要把我第二张图里的数据换成第一张图的格式，去掉第二张图里没有的数据，就可以连接上javdb
![image](https://user-images.githubusercontent.com/23073985/158361345-c824a6ad-33d0-4193-80b1-58d50deaa430.png)

**Comment by JadeButterfly** [comment]
看不懂你的格式是什么意思

**Comment by clggwater** [comment]
> 
把”xx”:”yy”,改成xx=yy;

**Comment by 2335eq** [comment]
所以大佬咋解决了？我搞了一晚上还是没搞明白

**Comment by clggwater** [comment]
> 所以大佬咋解决了？我搞了一晚上还是没搞明白

把本来是 
   " _cf_bm“:"xxxxxxxxxx",
   "over18":"1",
  改写成_cf_bm=xxxxxxxxxxx;over18=1这样的字符串，就行了。具体 需要哪些数据，看这张图
![image](https://user-images.githubusercontent.com/23073985/163761962-0b1640a6-adf8-49ba-85f0-de9356bb61df.png)

**Comment by JadeButterfly** [comment]
测试时能成功，但同步时404

**Comment by JadeButterfly** [comment]
> 测试时能成功，但同步时404

现在测试又失败了，难道被秒封了？
