### ISSUE TITLE
软件性能问题

### ISSUE THREAD

**Issue by spartawhy117** [hitchao/Jvedio#153]
# 反馈

最新版本的软件吃资源比较多，主要是3d性能上感觉还是有问题。

- 出现问题的版本：4.6.1.1

- 电脑系统：win11

# 描述：

之前一直使用笔记本就发现开启软件后，笔记本散热就有点起飞了。昨晚装了新的台式机使用2060运行程序发现，能吃掉2060 50%的3d性能，这个数据是在4k分辨率的屏幕下得到的。

# 日志文件：

无

**Comment by hitchao** [comment]
已修复
