### ISSUE TITLE
重复演员报错

### ISSUE THREAD

**Issue by vansto** [hitchao/Jvedio#16]
-----【2020/9/30-星期三 1:03:42】-----
Message=>未将对象引用设置到对象的实例。
StackTrace=>
    文件: D:\hitchao\Jvedio\Jvedio\ViewModel\VieModel_Main.cs 方法: <GetMoviebyActressAndVetioType>b__1 行数: 907
    文件: D:\hitchao\Jvedio\Jvedio\ViewModel\VieModel_Main.cs 方法: <GetMoviebyActressAndVetioType>b__0 行数: 907
    文件: D:\hitchao\Jvedio\Jvedio\ViewModel\VieModel_Main.cs 方法: GetMoviebyActressAndVetioType 行数: 905
    文件: D:\hitchao\Jvedio\Jvedio\WindowMain.xaml.cs 方法: ShowSameActor 行数: 1167

-----【2020/9/30-星期三 1:03:44】-----
Message=>未将对象引用设置到对象的实例。
StackTrace=>
    文件: D:\hitchao\Jvedio\Jvedio\WindowMain.xaml.cs 方法: ShowSameActor 行数: 1162

![无标题](https://user-images.githubusercontent.com/10329221/94590466-441eb300-02b9-11eb-9a34-87cfb1e4fc1f.png)

**Comment by hitchao** [comment]
已修复，感谢
