### ISSUE TITLE
求助及建议

### ISSUE THREAD

**Issue by XTWZXCV** [hitchao/Jvedio#160]
# 反馈

- 出现问题的版本：（如4.6.1.1）

- 电脑系统：（如 win 10）

# 描述：
演员信息同步不到的时候我尝试手动输入，但是输入之后好像不能保存，例如我先编辑一名演员信息保存之后编辑下一位演员，第二位编辑好保存之后第一位的信息就会消失，不知道是我哪里没设置好还是软件的问题，求帮助！！！另外这软件对于收藏党来说简直就是超级好用！！

**Comment by hitchao** [comment]
最新版已修复
