### ISSUE TITLE
无法编译，本地缺少ChaoControls.Style.dll这个库

### ISSUE THREAD

**Issue by maxioriv** [hitchao/Jvedio#161]
..\..\..\..\Visual_Studio_Project\chao-controls\ChaoControls.Style\bin\Debug\ChaoControls.Style.dll

由于缺少上面这个库，导致本地无法编译通过，能不能提供下呢？谢谢！

**Comment by hitchao** [comment]
可以，不过今天 github 突然没法推送了，下一次推送我加上

**Comment by hitchao** [comment]
可以了，你重新拉取代码后，重新编译即可
