### ISSUE TITLE
提示同步信息成功后，却并没有看到同步的信息。

### ISSUE THREAD

**Issue by iamwanghui** [hitchao/Jvedio#165]
- 出现问题的版本：5.0
- 电脑系统：win10

# 描述：

选择“同步信息”后，提示任务成功，但电影封面并没有更新。
bigpic目录下也没有下载成功文件。

另外：之前的“全部同步”按钮怎么找不到了。 

# 日志文件：

-----【2022/5/4 星期三 21:18:23】-----
Message=>未能找到路径“E:\Repositores\Jvedio-master\Jvedio-WPF\Release\public\File\DataBase”的一部分。
StackTrace=>
    文件: E:\Repositores\Jvedio-master\Jvedio-WPF\Jvedio\Utils\FileProcess\DirHelper.cs 方法: TryMoveDir 行数: 68

**Comment by hitchao** [comment]
额，这个 5.0 还是内测版的……还没发布

**Comment by iamwanghui** [comment]
> 额，这个 5.0 还是内测版的……还没发布

哈哈，没关系。我先装一个VS2022跟一下代码试试。
