### ISSUE TITLE
希望能增加 演员的排序，收藏和列表排序功能

### ISSUE THREAD

**Issue by rrkyd** [hitchao/Jvedio#17]
大佬太强了。提两个小建议，第一，当前演员没有排序功能（比如根据影片多少），也无法加入收藏夹，比较不方便。 还有就是不知道后续能不能加入播放列表功能， 就是根据年份，演员，类别等等过滤出一个新列表，可以叠加，具体可以参考KODI的smart list。

**Comment by jvedio** [comment]
好的，后续可能会加入
