### ISSUE TITLE
项目有build指南吗？

### ISSUE THREAD

**Issue by spartawhy117** [hitchao/Jvedio#175]
用起来有一些细节的地方蛋疼，想fork下来看看有没有能帮忙改进的地方

主要是作者有没有共享的软件需求设计文档之类的链接，就怕自己的分支上改了不和老哥的想法，想先看看5.0的路线图或者计划的功能设计

**Comment by hitchao** [comment]
这两天在做发布的一些内容，文档包括用户文档，编译构建过程都在写着，周末前差不多能写完。

另外非常感谢能够一起写jvedio，不过可能得等到周末左右我才推送最新版本，因为项目结构发生挺大变化，代码变了挺多，我这边还没提交。

最后，不用担心什么，pr就完了！

**Comment by RobertChou** [comment]
想问下何时会把5.0的包release出来？

**Comment by hitchao** [comment]
> 想问下何时会把5.0的包release出来？

点更新就能用了，不过是内测版本

**Comment by RobertChou** [comment]
> > 想问下何时会把5.0的包release出来？
> 
> 点更新就能用了，不过是内测版本

点升级，查询到最新版本时4.6.1.1，没有查到5.0版本啊

**Comment by hitchao** [comment]
> > > 想问下何时会把5.0的包release出来？
> > 
> > 
> > 点更新就能用了，不过是内测版本
> 
> 点升级，查询到最新版本时4.6.1.1，没有查到5.0版本啊

这个没关系，只是没通知是最新版，点更新就是 5.0 内测

**Comment by RobertChou** [comment]
> > > > 想问下何时会把5.0的包release出来？
> > > 
> > > 
> > > 点更新就能用了，不过是内测版本
> > 
> > 
> > 点升级，查询到最新版本时4.6.1.1，没有查到5.0版本啊
> 
> 这个没关系，只是没通知是最新版，点更新就是 5.0 内测

升级了，结果打不开了。。。怎么破，win11 64位

**Comment by hitchao** [comment]
> > > > > 想问下何时会把5.0的包release出来？
> > > > 
> > > > 
> > > > 点更新就能用了，不过是内测版本
> > > 
> > > 
> > > 点升级，查询到最新版本时4.6.1.1，没有查到5.0版本啊
> > 
> > 
> > 这个没关系，只是没通知是最新版，点更新就是 5.0 内测
> 
> 升级了，结果打不开了。。。怎么破，win11 64位

额打不开的话也没事，你的数据还在，如果有 database 目录就把 database 目录复制回 4.6.1.1，如果没有 database 文件夹，数据应该就是在 data/用户名/olddata 下

**Comment by RobertChou** [comment]
> > > > > > 想问下何时会把5.0的包release出来？
> > > > > 
> > > > > 
> > > > > 点更新就能用了，不过是内测版本
> > > > 
> > > > 
> > > > 点升级，查询到最新版本时4.6.1.1，没有查到5.0版本啊
> > > 
> > > 
> > > 这个没关系，只是没通知是最新版，点更新就是 5.0 内测
> > 
> > 
> > 升级了，结果打不开了。。。怎么破，win11 64位
> 
> 额打不开的话也没事，你的数据还在，如果有 database 目录就把 database 目录复制回 4.6.1.1，如果没有 database 文件夹，数据应该就是在 data/用户名/olddata 下

把4.6.1.1的包覆盖回来，又能打开了，数据没问题，就是想想5.0正式版啥时候能出来？

**Comment by hitchao** [comment]
> 

不好说，最近在检视代码

**Comment by hitchao** [comment]
开发者文档已提交
