### ISSUE TITLE
5.0版本本地视频无法同步本地nfo

### ISSUE THREAD

**Issue by SnailInLeaves** [hitchao/Jvedio#177]
### 注意

请勿上传任何**暴力、色情、恐怖**的信息或图片！

### 反馈/建议

- 出现问题的版本：（如4.5.0.0）
- 电脑系统：（如 win 10）
- 提出的建议：xxx

### 描述：

详细说明前因后果、操作步骤。

### 日志文件：

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/Introduction_3)

**Comment by hitchao** [comment]
已解决
