### ISSUE TITLE
项目编译问题

### ISSUE THREAD

**Issue by spartawhy117** [hitchao/Jvedio#179]
Nuget还原后，有三个包提示已废弃

![image](https://user-images.githubusercontent.com/9450028/174495435-bc48e942-44de-4e6d-a4b9-ca2111473085.png)

这三个包需要怎么处理吗？

**Comment by spartawhy117** [comment]
另外升級到5.0.0 目前发现两个显著bug
1. 升级选项提示4.6.1
2. 电影的缩略图全部找不到，点击影片查找缩略图位置，提示的也是未查找到.gif后缀的文件，这个应该是找错文件类型了

**Comment by spartawhy117** [comment]
另外两个问题：
1. 发现迁移过后， 搜刮器的配置丢失
2. 不能新建搜刮器

**Comment by hitchao** [comment]
> Nuget还原后，有三个包提示已废弃
> 
> ![image](https://user-images.githubusercontent.com/9450028/174495435-bc48e942-44de-4e6d-a4b9-ca2111473085.png)
> 
> 这三个包需要怎么处理吗？

这个没关系

**Comment by hitchao** [comment]
> 另外升級到5.0.0 目前发现两个显著bug
> 1. 升级选项提示4.6.1
> 2. 电影的缩略图全部找不到，点击影片查找缩略图位置，提示的也是未查找到.gif后缀的文件，这个应该是找错文件类型了

这个也没关系，升级的版本和提示由另一个项目jvedioupdate进行通知
缩略图的后缀会从jpg一直找到png bmp jpeg最后到gif因此最后gif没有就显示gif

**Comment by hitchao** [comment]
> 另外两个问题：
> 1. 发现迁移过后， 搜刮器的配置丢失
> 2. 不能新建搜刮器

搜刮器也在另一个项目，我晚点整理一下各个项目的关系

**Comment by spartawhy117** [comment]
> > 另外升級到5.0.0 目前发现两个显著bug
> > 
> > 1. 升级选项提示4.6.1
> > 2. 电影的缩略图全部找不到，点击影片查找缩略图位置，提示的也是未查找到.gif后缀的文件，这个应该是找错文件类型了
> 
> 这个也没关系，升级的版本和提示由另一个项目jvedioupdate进行通知 缩略图的后缀会从jpg一直找到png bmp jpeg最后到gif因此最后gif没有就显示gif

我的 图片还在之前的目录下，但是5.0版本目前就是提示找不到对应电影的缩略图，不知道要怎么解决

**Comment by spartawhy117** [comment]
> > 另外两个问题：
> > 
> > 1. 发现迁移过后， 搜刮器的配置丢失
> > 2. 不能新建搜刮器
> 
> 搜刮器也在另一个项目，我晚点整理一下各个项目的关系

之前的搜刮器配置直接丢失了，这个目前是不是不能恢复了。然后新建某个jav的搜刮器只能添加默认的两个搜刮器插件后再手动编辑？

**Comment by hitchao** [comment]
> > > 另外升級到5.0.0 目前发现两个显著bug
> > > 
> > > 1. 升级选项提示4.6.1
> > > 2. 电影的缩略图全部找不到，点击影片查找缩略图位置，提示的也是未查找到.gif后缀的文件，这个应该是找错文件类型了
> > 
> > 这个也没关系，升级的版本和提示由另一个项目jvedioupdate进行通知 缩略图的后缀会从jpg一直找到png bmp jpeg最后到gif因此最后gif没有就显示gif
> 
> 我的 图片还在之前的目录下，但是5.0版本目前就是提示找不到对应电影的缩略图，不知道要怎么解决

得设置一下图片的路径模式，可以采用绝对路径

**Comment by RobertChou** [comment]
是准备发布5.0的包了吗？

**Comment by hitchao** [comment]
> 是准备发布5.0的包了吗？

是的

**Comment by hitchao** [comment]
已修复
