### ISSUE TITLE
批量下载无响应

### ISSUE THREAD

**Issue by kenz1025** [hitchao/Jvedio#18]
感谢作者辛苦更新
批量下载现在就是两种反应
一种就是被系统挂起然后进程自己消失
另一种就是进行到一定程度后进度就一直停止不跑了
挂代理/直连都是一样，系统win10x64

**Comment by kenz1025** [comment]
感谢作者辛苦更新
批量下载现在就是两种反应
一种就是被系统挂起然后进程自己消失
另一种就是进行到一定程度后进度就一直停止不跑了
挂代理/直连都是一样，系统win10x64

**Comment by jvedio** [comment]
这个有点 bug 目前还在修复中
