### ISSUE TITLE
5.0新版本无法识别演员。nfo信息中包含演员但是识别不出来

### ISSUE THREAD

**Issue by yunxiujun** [hitchao/Jvedio#180]
如标题5.0新版本无法识别演员。nfo信息中包含演员但是识别不出来
![image](https://user-images.githubusercontent.com/72745658/174713245-bdaefa94-1b35-4de2-8a1a-92a9dd29259b.png)

**Comment by yunxiujun** [comment]
所有nfo信息都可以拉出来就是不能拉出演员。。选择的相对路径模式。

**Comment by hitchao** [comment]
这个确实存在，有空我修复下

**Comment by hitchao** [comment]
已修复，点击更新即可
