### ISSUE TITLE
问题反馈：特定格式的文件名无法正确自动识别

### ISSUE THREAD

**Issue by LKCasso** [hitchao/Jvedio#182]
### 反馈

- 出现问题的版本：4.6.1.1 / 5.0.0.0
- 电脑系统：Windows 11

### 描述：

> 在扫描本地文件夹时，遇到类似文件名为“OMAMA-018B”、“17ID-005”、“AOZ-288Z”的文件时，扫描至软件后变成“OMAMA-018”、“ID-005”、“AOZ-288”，导致BUS刮削失败。

**Comment by RobertChou** [comment]
> ### 反馈
> * 出现问题的版本：4.6.1.1 / 5.0.0.0
> * 电脑系统：Windows 11
> 
> ### 描述：
> > 在扫描本地文件夹时，遇到类似文件名为“OMAMA-018B”、“17ID-005”、“AOZ-288Z”的文件时，扫描至软件后变成“OMAMA-018”、“ID-005”、“AOZ-288”，导致BUS刮削失败。

5.0还不能刮削吧？

**Comment by LKCasso** [comment]
是的，不能刮削，但是问题是出在扫描入库阶段，文件名不能正确识别。

**Comment by LKCasso** [comment]
> > ### 反馈
> > 
> > * 出现问题的版本：4.6.1.1 / 5.0.0.0
> > * 电脑系统：Windows 11
> > 
> > ### 描述：
> > > 在扫描本地文件夹时，遇到类似文件名为“OMAMA-018B”、“17ID-005”、“AOZ-288Z”的文件时，扫描至软件后变成“OMAMA-018”、“ID-005”、“AOZ-288”，导致BUS刮削失败。
> 
> 5.0还不能刮削吧？

是的，不能刮削，但是问题不在刮削上面，是扫描本地文件时，文件名不能正确识别的问题。

**Comment by hitchao** [comment]
已解决
