### ISSUE TITLE
多选后添加标记也只能一个一个添加，还有就是希望出一个视频分辨率的自动显示功能，之前的巴士的HD标记是根据文件大小来的，480p的只要超过3g了也是显示HD

### ISSUE THREAD

**Issue by 10929485** [hitchao/Jvedio#183]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：（如5.0.0.0）
- 电脑系统：（如 win 10）
- 提出的建议：xxx

### 描述：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by hitchao** [comment]
已修复批量添加标记
