### ISSUE TITLE
版本升级到4.0以后，运行起来非常卡，不知为何

### ISSUE THREAD

**Issue by tgfcer** [hitchao/Jvedio#19]
原来2.x的时候，运行顺畅，到了4.x以后就卡成狗，不知是什么原因，系统是Win10 home 64bit

**Comment by RobertChou** [comment]
感觉c#的版本比之前的winform的要卡

**Comment by tgfcer** [comment]
不过我卡成狗，是不是win10缺点什么东西或者设置不对啊？

**Comment by RobertChou** [comment]
> 
> 
> 不过我卡成狗，是不是win10缺点什么东西或者设置不对啊？

应该不是win10问题吧，win10现在很普遍了，不知道是不是C#的form的执行效率

**Comment by tgfcer** [comment]
看issue list, 我是个案，不知道哪里出了问题，不知老大有经验吗？

**Comment by hitchao** [comment]
我在笔记本上有点小卡，台式机很流畅

**Comment by op123355569** [comment]
我也很卡
