### ISSUE TITLE
5.0版本无法刮削

### ISSUE THREAD

**Issue by 307590317** [hitchao/Jvedio#192]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：5.0.0.0
- 电脑系统：win 10
- 提出的建议：能够刮削

### 描述：

按照文档配置刮削器之后依然不能刮削
![image](https://user-images.githubusercontent.com/27839893/180607566-ee21688d-8913-44fe-a20e-b7ac2bc10dee.png)

提示无对应刮削器刮削
![image](https://user-images.githubusercontent.com/27839893/180607572-fdebb879-7431-43fe-b727-f6736ca5e068.png)

希望能够刮削或者告诉我改怎么配置才能刮削

**Comment by hitchao** [comment]
目前刮削还在开发中

**Comment by hitchao** [comment]
已修复
