### ISSUE TITLE
使用access数据导入功能闪退

### ISSUE THREAD

**Issue by Petrchor** [hitchao/Jvedio#194]
使用access数据导入功能闪退
作者大大，想问一下这个access数据导入功能的mdb文件是要特定格式填入番号才行吗？我把带番号 Excel导入access中 得到mdb文件但是软件却闪退导不进去，试着加了视频后缀名也不行，想问一下是什么原因

**Comment by hitchao** [comment]
access 数据仅 3.0 可用
