### ISSUE TITLE
开源开发

### ISSUE THREAD

**Issue by Bu-Chuan** [hitchao/Jvedio#2]
之前大佬你在压缩包里放了vb的源代码，我本来想给你发私信看不能不能帮一些忙，但是没有论坛金钱没有联系到你。我对JavaScript比较熟悉，如果要开发网页端的话，可以联系我。

**Comment by hitchao** [comment]
非常感谢你的热心~
但是网页端不知道以后还会不会开发，如果要开发网页端，可能会是一个简单的评分或者回复功能


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bu-Chuan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月4日(星期六) 晚上8:08
收件人:&nbsp;"hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hitchao/Javedio-2.0] 开源开发 (#2)




之前大佬你在压缩包里放了vb的源代码，我本来想给你发私信看不能不能帮一些忙，但是没有论坛金钱没有联系到你。我对JavaScript比较熟悉，如果要开发网页端的话，可以联系我。

**Comment by Bu-Chuan** [comment]
回复的好快哈哈。
我指的网页端也还是本地运行的，读取本地数据库然后在浏览器里进行展示什么的，不需要做成网站或者论坛。而且我觉得做回复、评分什么的在线功能，可能会触线~~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hitchao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月4日(星期六) 晚上8:19
收件人:&nbsp;"hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送:&nbsp;"浪行在川"<1637091466@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hitchao/Javedio-2.0] 开源开发 (#2)



非常感谢你的热心~ 
 但是网页端不知道以后还会不会开发，如果要开发网页端，可能会是一个简单的评分或者回复功能 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Bu-Chuan"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年1月4日(星期六) 晚上8:08 
 收件人:&amp;nbsp;"hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[hitchao/Javedio-2.0] 开源开发 (#2) 
 
 
 
 
 之前大佬你在压缩包里放了vb的源代码，我本来想给你发私信看不能不能帮一些忙，但是没有论坛金钱没有联系到你。我对JavaScript比较熟悉，如果要开发网页端的话，可以联系我。

**Comment by hitchao** [comment]
你这个想法很好!
如果能在web上实现，就不用去写这么多ui了，我之前是想用html写，后来发现对文件夹操作太麻烦了，现在想想，可以采用exe扫描，封装web进行操作，这样也不用下载了，直接就是盗链人家的图片信息


 
---原始邮件---
发件人: "Bu-Chuan"<notifications@github.com&gt;
发送时间: 2020年1月4日(星期六) 晚上8:26
收件人: "hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"hitchao"<2415923016@qq.com&gt;;
主题: Re: [hitchao/Javedio-2.0] 开源开发 (#2)


回复的好快哈哈。 
 我指的网页端也还是本地运行的，读取本地数据库然后在浏览器里进行展示什么的，不需要做成网站或者论坛。而且我觉得做回复、评分什么的在线功能，可能会触线~~~ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"hitchao"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年1月4日(星期六) 晚上8:19 
 收件人:&amp;nbsp;"hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"浪行在川"<1637091466@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [hitchao/Javedio-2.0] 开源开发 (#2) 
 
 
 
 非常感谢你的热心~  
  但是网页端不知道以后还会不会开发，如果要开发网页端，可能会是一个简单的评分或者回复功能  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"Bu-Chuan"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年1月4日(星期六) 晚上8:08  
  收件人:&amp;amp;nbsp;"hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[hitchao/Javedio-2.0] 开源开发 (#2)  
   
   
   
   
  之前大佬你在压缩包里放了vb的源代码，我本来想给你发私信看不能不能帮一些忙，但是没有论坛金钱没有联系到你。我对JavaScript比较熟悉，如果要开发网页端的话，可以联系我。

**Comment by Bu-Chuan** [comment]
嗯嗯我觉得挺好的，把扫描本地文件和UI展示分开操作，写起来也很方便，就是操作起来有点麻烦。有文件改动的时候，先要运行exe，然后再打开网页。还有一个问题就是html只能读，不能修改本地文件，要进行label或者删除操作很麻烦。

**Comment by yjd** [comment]
看了下，感觉比AV_Data_Capture合理。
希望说明文档能完善一下。

**Comment by hitchao** [comment]
嗯嗯，最近正在完善


 
---原始邮件---
发件人: "yjd"<notifications@github.com&gt;
发送时间: 2020年1月28日(星期二) 凌晨0:55
收件人: "hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"hitchao"<2415923016@qq.com&gt;;
主题: Re: [hitchao/Javedio-2.0] 开源开发 (#2)



看了下，感觉比AV_Data_Capture合理。
 希望说明文档能完善一下。
