### ISSUE TITLE
希望缩略图能够显示完全

### ISSUE THREAD

**Issue by aiwandexiong** [hitchao/Jvedio#206]
在自定外观那里把东西都点掉后，发现下半部分是黑的，缩略图是直接给对半切了放文字。。。
就emby那样挺好的
![搜狗截图22年09月05日0506_2](https://user-images.githubusercontent.com/112748580/188333502-35a4ff78-08ec-480b-8e99-1ee18c0e1839.png)
![搜狗截图22年09月05日0505_1](https://user-images.githubusercontent.com/112748580/188333472-3c9ea7db-67cc-4a8f-85c0-2dda490d04bd.png)

**Comment by hitchao** [comment]
已修复
