### ISSUE TITLE
缺少引用的第三方库 无法编译

### ISSUE THREAD

**Issue by zc910704** [hitchao/Jvedio#208]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议
项目里引用了第三方库，路径好像不在根目录里，能不能添加到工程里或者上传dll
```
    <Reference Include="SuperControls.Style">
      <HintPath>..\..\..\..\SuperStudio\SuperControls\SuperControls.Style\bin\Debug\SuperControls.Style.dll</HintPath>
    </Reference>
```

**Comment by zc910704** [comment]
在Reference文件夹找到了

**Comment by hitchao** [comment]
没想到还有人也在用😂，我在建个分支吧，避免我自己的修改影响到主分支了

**Comment by hitchao** [comment]
没想到还有人也在用😂，我在建个分支吧，避免我自己的修改影响到主分支了

**Comment by hitchao** [comment]
没想到还有人也在用😂，我在建个分支吧，避免我自己的修改影响到主分支了

**Comment by zc910704** [comment]
可以把新的插件库也传上么？传个demo的样子有时间可以照着做

**Comment by hitchao** [comment]
> 可以把新的插件库也传上么？传个demo的样子有时间可以照着做

这个得晚点，插件还没完善
