### ISSUE TITLE
感谢大佬的付出

### ISSUE THREAD

**Issue by XTWZXCV** [hitchao/Jvedio#213]
等了这么久终于等到5.0的刮削了，这个管理软件用着太舒服了，真心感谢大佬，RESPECT

**Comment by hitchao** [comment]
谢谢😁

**Comment by hitchao** [comment]
谢谢😁

**Comment by HawnHan** [comment]
你们FC2的刮削正常吗，我的报DLL加载错误

**Comment by 307590317** [comment]
> HawnHan
我也遇到了相同的问题，想问下你解决了么？
![Uploading image.png…]()

**Comment by hitchao** [comment]
5.2 已修复
