### ISSUE TITLE
为什么下载的最新的5.0没有插件

### ISSUE THREAD

**Issue by evesky** [hitchao/Jvedio#214]
[最新的5.0已经关闭了青少年模式了，选项中没有插件设置。

**Comment by hitchao** [comment]
> [最新的5.0已经关闭了青少年模式了，选项中没有插件设置。
> 

左下角的设置里有插件选项

**Comment by evesky** [comment]
我的设置里 没有插件选项

**Comment by spartawhy117** [comment]
> > [最新的5.0已经关闭了青少年模式了，选项中没有插件设置。
> 
> 左下角的设置里有插件选项

我也是关闭了青少年模式，设置里面没有找到插件选项，而且添加不了搜刮器

**Comment by goodryb** [comment]
我也是，5.0版本确实没有插件选项

> > > [最新的5.0已经关闭了青少年模式了，选项中没有插件设置。
> > 
> > 
> > 左下角的设置里有插件选项
> 
> 我也是关闭了青少年模式，设置里面没有找到插件选项，而且添加不了搜刮器

**Comment by hitchao** [comment]
5.2 已修复
