### ISSUE TITLE
指定预览图为海报的功能消失了

### ISSUE THREAD

**Issue by kenz1025** [hitchao/Jvedio#215]
- 出现问题的版本：5.0.0.0
- 电脑系统： win 10
- 提出的建议：

### 描述：
原来4.6版本是有这个功能的，右键预览图可以指定为海报，可以恢复这个功能吗？有些时候很有用
现在直接拖拽影片到程序后主页不会显示新加入，要点下左边的所有视频才会刷新主页

**Comment by hitchao** [comment]
版本 [Jvedio-5.4](https://github.com/hitchao/Jvedio/releases/tag/5.4) 已修复
