### ISSUE TITLE
下载插件就闪退，把插件删除后就正常，导入不了视频

### ISSUE THREAD

**Issue by CJQ789** [hitchao/Jvedio#224]
![1665856263234](https://user-images.githubusercontent.com/115893407/196001116-faa68b1b-ecd8-4af7-afaa-d0fea9ce28f5.png)

**Comment by CJQ789** [comment]
2022-10-16 01:03:30.395 => [Warning] 公告解析错误 
2022-10-16 01:07:16.373 => [Warning] [DispatcherUnhandledException] Jvedio 出现了一些问题，将退出 
2022-10-16 01:08:55.300 => [Warning] [DispatcherUnhandledException] Jvedio 出现了一些问题，将退出 
2022-10-16 01:10:30.977 => [Warning] [DispatcherUnhandledException] Jvedio 出现了一些问题，将退出 
2022-10-16 01:10:48.997 => [Warning] [DispatcherUnhandledException] Jvedio 出现了一些问题，将退出 
2022-10-16 01:13:14.686 => [Warning] [DispatcherUnhandledException] Jvedio 出现了一些问题，将退出 
2022-10-16 01:13:31.901 => [Warning] [DispatcherUnhandledException] Jvedio 出现了一些问题，将退出 
2022-10-16 01:22:52.323 => [Warning] [DispatcherUnhandledException] Jvedio 出现了一些问题，将退出 
2022-10-16 01:26:51.536 => [Warning] [DispatcherUnhandledException] Jvedio 出现了一些问题，将退出 
2022-10-16 01:50:15.937 => [Warning] [DispatcherUnhandledException] Jvedio 出现了一些问题，将退出 
2022-10-16 01:52:43.100 => [Warning] [DispatcherUnhandledException] Jvedio 出现了一些问题，将退出

**Comment by CJQ789** [comment]
[2022/10/16 1:02:02]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:06:47]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:06:47]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:06:47]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:07:11]
[Message] 值不能为 null。
参数名: value
[StackTrace] 
 
[2022/10/16 1:07:16]
[Message] “JvedioLib.Security.Encrypt”的类型初始值设定项引发异常。
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Utils\Extern\JvedioLib.cs 方法: GetFileMD5 行数: 68
文件: \Jvedio-WPF\Jvedio\Core\Plugins\Crawler\CrawlerManager.cs 方法: LoadAllCrawlers 行数: 46
文件: \Jvedio-WPF\Jvedio\WindowStartUp.xaml.cs 方法: MoveNext 行数: 102

[2022/10/16 1:08:07]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:08:07]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:08:07]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:08:53]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:08:53]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:08:53]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:08:55]
[Message] “JvedioLib.Security.Encrypt”的类型初始值设定项引发异常。
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Utils\Extern\JvedioLib.cs 方法: GetFileMD5 行数: 68
文件: \Jvedio-WPF\Jvedio\Core\Plugins\Crawler\CrawlerManager.cs 方法: LoadAllCrawlers 行数: 46
文件: \Jvedio-WPF\Jvedio\WindowStartUp.xaml.cs 方法: MoveNext 行数: 102

[2022/10/16 1:09:50]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:09:50]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:09:50]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:10:27]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:10:27]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:10:27]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:10:30]
[Message] “JvedioLib.Security.Encrypt”的类型初始值设定项引发异常。
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Utils\Extern\JvedioLib.cs 方法: GetFileMD5 行数: 68
文件: \Jvedio-WPF\Jvedio\Core\Plugins\Crawler\CrawlerManager.cs 方法: LoadAllCrawlers 行数: 46
文件: \Jvedio-WPF\Jvedio\WindowStartUp.xaml.cs 方法: MoveNext 行数: 102

[2022/10/16 1:10:47]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:10:47]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:10:47]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:10:48]
[Message] “JvedioLib.Security.Encrypt”的类型初始值设定项引发异常。
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Utils\Extern\JvedioLib.cs 方法: GetFileMD5 行数: 68
文件: \Jvedio-WPF\Jvedio\Core\Plugins\Crawler\CrawlerManager.cs 方法: LoadAllCrawlers 行数: 46
文件: \Jvedio-WPF\Jvedio\WindowStartUp.xaml.cs 方法: MoveNext 行数: 102

[2022/10/16 1:11:17]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:11:17]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:11:17]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:13:12]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:13:12]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:13:12]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:13:14]
[Message] “JvedioLib.Security.Encrypt”的类型初始值设定项引发异常。
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Utils\Extern\JvedioLib.cs 方法: GetFileMD5 行数: 68
文件: \Jvedio-WPF\Jvedio\Core\Plugins\Crawler\CrawlerManager.cs 方法: LoadAllCrawlers 行数: 46
文件: \Jvedio-WPF\Jvedio\WindowStartUp.xaml.cs 方法: MoveNext 行数: 102

[2022/10/16 1:13:29]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:13:29]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:13:29]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:13:31]
[Message] “JvedioLib.Security.Encrypt”的类型初始值设定项引发异常。
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Utils\Extern\JvedioLib.cs 方法: GetFileMD5 行数: 68
文件: \Jvedio-WPF\Jvedio\Core\Plugins\Crawler\CrawlerManager.cs 方法: LoadAllCrawlers 行数: 46
文件: \Jvedio-WPF\Jvedio\WindowStartUp.xaml.cs 方法: MoveNext 行数: 102

[2022/10/16 1:14:26]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:14:26]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:14:26]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:16:56]
[Message] 值不能为 null。
参数名: value
[StackTrace] 
 
[2022/10/16 1:19:10]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:19:10]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:19:10]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:22:49]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:22:49]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:22:49]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:22:52]
[Message] “JvedioLib.Security.Encrypt”的类型初始值设定项引发异常。
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Utils\Extern\JvedioLib.cs 方法: GetFileMD5 行数: 68
文件: \Jvedio-WPF\Jvedio\Core\Plugins\Crawler\CrawlerManager.cs 方法: LoadAllCrawlers 行数: 46
文件: \Jvedio-WPF\Jvedio\WindowStartUp.xaml.cs 方法: MoveNext 行数: 102

[2022/10/16 1:24:03]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:24:03]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:24:03]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:26:45]
[Message] 值不能为 null。
参数名: value
[StackTrace] 
 
[2022/10/16 1:26:51]
[Message] 未找到“Success”资源。
[StackTrace] 
 
[2022/10/16 1:27:06]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:38:52]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:38:52]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:38:52]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:41:34]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:41:34]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:41:34]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:50:15]
[Message] “JvedioLib.Security.Encrypt”的类型初始值设定项引发异常。
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Utils\Extern\JvedioLib.cs 方法: GetFileMD5 行数: 68
文件: \Jvedio-WPF\Jvedio\Core\Plugins\Crawler\CrawlerManager.cs 方法: LoadAllCrawlers 行数: 46
文件: \Jvedio-WPF\Jvedio\WindowStartUp.xaml.cs 方法: MoveNext 行数: 102

[2022/10/16 1:50:26]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:50:26]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:50:26]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:52:43]
[Message] “JvedioLib.Security.Encrypt”的类型初始值设定项引发异常。
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Utils\Extern\JvedioLib.cs 方法: GetFileMD5 行数: 68
文件: \Jvedio-WPF\Jvedio\Core\Plugins\Crawler\CrawlerManager.cs 方法: LoadAllCrawlers 行数: 46
文件: \Jvedio-WPF\Jvedio\WindowStartUp.xaml.cs 方法: MoveNext 行数: 102

[2022/10/16 1:54:08]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:54:08]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2022/10/16 1:54:08]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

**Comment by hitchao** [comment]
5.2 已修复
