### ISSUE TITLE
bug 太多了

### ISSUE THREAD

**Issue by aide315** [hitchao/Jvedio#225]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：（5.0.0.0）
- 电脑系统：（ win 10）
- 提出的建议：bug

### 描述：
1、单独导入电影截图导入
2、gif生成老是报错，给定关键字不在字典中

**Comment by hwadong860** [comment]
Bug太多了，我不忍心写…

**Comment by hopradio** [comment]
这玩意就是半成品……本来像替换AV_Data_Capture 的

**Comment by hitchao** [comment]
5.2 已修复
