### ISSUE TITLE
BUG反馈以及建议

### ISSUE THREAD

**Issue by Bouncysig18** [hitchao/Jvedio#227]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议
BUG1. :界面选择无图后，对无图以及无同步信息的番号进行同步，同步后该番号仍然会存在勾选无图显示的界面中。虽然该番号已经成功同步了
建议1：扫描影片文件时候，扫描结果十分不友好。不友好的地方有：过多的冗余信息（图片，nfo等），并且不能对扫描结果进行筛选（例如只显示没有导入的影片，我很想知道我为什么没有导入，因为过多冗余信息我也不知道报错信息有哪几种也无法进行筛选）。我的强烈建议：如同4.6版本一样一定要提供txt文本，以及我扫描路径下如果存在两个不同路径的相同影片文件（一个带字幕一个不带字幕），我需要扫描后一定要提供给我这2个文件的路径，方便我对影片进行删减处理。

- 出现问题的版本: 5.000
- 电脑系统：Win10（如 win 10）

**Comment by hitchao** [comment]
5.2 已修复
