### ISSUE TITLE
依然无法识别XXX-123C这样的影片

### ISSUE THREAD

**Issue by mooonfire** [hitchao/Jvedio#228]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：（5.0.0.0）
- 电脑系统：（win 10）

### 描述：

使用javbus.com作为服务器，依然无法同步类似ABC-123C这种文件的信息

**Comment by wangwenjie0** [comment]
确实是，需要自己手动修改后缀...

**Comment by mooonfire** [comment]
> 确实是，需要自己手动修改后缀...

这种如何修改后缀，修改文件名没用吧

**Comment by hitchao** [comment]
实测可识别，需要视频文件才行
