### ISSUE TITLE
分段视频人工处理后，再次扫描文件夹，重复导入

### ISSUE THREAD

**Issue by AcGW-RErCotWd** [hitchao/Jvedio#230]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：5.0.0.0
- 电脑系统：win 10
- 提出的建议：修改扫描handler，如果此文件出现在path或者subsection里，不再重复导入

### 日志文件：

NA

**Comment by hitchao** [comment]
分段视频需要按照指定格式

软件默认可识别以下几种分段视频

XXX-001-1, XXX-001-2, XXX-001-3
XXX-001_1, XXX-001_2, XXX-001_3
XXX-001cd1, XXX-001cd2, XXX-001cd3
XXX-001fhd1, XXX-001fhd2, XXX-001fhd3
XXX-001A, XXX-001B, XXX-001C
