### ISSUE TITLE
无法识别任何视频文件

### ISSUE THREAD

**Issue by tonystudy1** [hitchao/Jvedio#231]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：5.0
- 电脑系统：win10
- 提出的建议：无法识别视频文件

### 描述：

新建一个库
然后导入视频，选中有视频文件的文件夹确认后，无任何视频导入
视频格式为MP4，不知道是哪里除了问题，点击导入详情
结果为 总数为0 导入为0 未导入为0
有的时候甚至能识别ini的文件都无法识别MP4的文件
之前说导入视频需要识别码？如何添加识别码呢？

**Comment by hitchao** [comment]
扫描后，点击【查看异常】看看有无日志

**Comment by iframeworker** [comment]
我也是这样

**Comment by hitchao** [comment]
5.2 已修复

**Comment by dearpanan** [comment]
还是没有修复
