### ISSUE TITLE
1插件栏没有教程插件2挂削器显示未启用

### ISSUE THREAD

**Issue by 192122588** [hitchao/Jvedio#235]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：（如5.0.0.0）
- 电脑系统：（如 win 10）
- 提出的建议：求大佬解答，1没有插件2挂削器显示未启用

### 描述：

4.6版本一同步就闪退，5.0版本这个没有挂削器视频无法更新信息
挂削器处显示未启用，青少年模式已关闭，这个怎么操作添加网址呢
![QQ截图20221116201421](https://user-images.githubusercontent.com/118358091/202178143-9b3e49cd-70ae-4d16-8aee-578e9deb08cb.png)
![QQ截图20221116201440](https://user-images.githubusercontent.com/118358091/202178156-81b99a05-a379-4843-8e17-11d0a6ae0d71.png)

**Comment by hitchao** [comment]
点击插件，然后启用就行了

**Comment by 192122588** [comment]
> 点击插件，然后启用就行了

我不太明白您的意思，我选择插件这里只有几个皮肤插件，并没有IMDB爬虫，看您的新手教程里是没有连接上GitHub的原因吗，如何添加IMDB爬虫插件呢
![QQ截图20221117173817](https://user-images.githubusercontent.com/118358091/202411017-0f050d9e-46f7-4430-ac8f-e5359ff5e9f0.png)
![QQ截图20221117173840](https://user-images.githubusercontent.com/118358091/202411023-56292869-a752-4f9b-8acc-6567826cf3cf.png)

**Comment by hitchao** [comment]
imdb插件目前有点问题，还在修复

**Comment by hitchao** [comment]
5.2 已修复
