### ISSUE TITLE
同步信息丢失以及77%卡死

### ISSUE THREAD

**Issue by Bouncysig18** [hitchao/Jvedio#237]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：5.0
- 电脑系统：win11
- 提出的建议：BUG

### 描述：
同步的时候很容易卡影片演员77%
明明之前同步同步不了部分信息，比如发行日期。但多次重复同步又能成功同步

**Comment by hitchao** [comment]
5.2 已修复
