### ISSUE TITLE
分类 系列 模块问题

### ISSUE THREAD

**Issue by 10929485** [hitchao/Jvedio#239]
1、分类、系列和标签的那栏没拖动条，显示不全 
2、系列里字体不一和带空格的可能就分成两个（字体甚至我都没看出来区别，但就是不在一起）演员部分也有同样问题，啥都一样就是分两个
3、新版有概率崩溃，一堆弹框然后就崩了
4、修正和无修正建议加一个点击功能，点一下分别显示各部分
5、可以看出来作者努力往非粉色软件发展然后变现，但除了粉色存片之外的大众的需求不能说是趋之若鹜吧，也可以说是无人问津，又不是几年前网络不发达的音像店，谁用这玩意存正经电影。我出个主意，这个软件可以做影视剪辑的素材前库，跟pr之间做个桥，加个标注分类等功能应该能有UP主花钱用

**Comment by hitchao** [comment]
并不准备变现😂只是为了不那么张扬

**Comment by xiaoxuan1991** [comment]
> 并不准备变现😂只是为了不那么张扬

完全公益的嘛,建议可以加个自愿捐款啥的,希望软件越来越好,

**Comment by hitchao** [comment]
5.2 已修复
