### ISSUE TITLE
存在以及无图tag存在bug

### ISSUE THREAD

**Issue by Bouncysig18** [hitchao/Jvedio#240]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议
1. 存在tag和不存在tag似乎反过来
2. 无图tag会显示以前已经同步了的影片

- 出现问题的版本：5.0
- 电脑系统：（如 win 10）
- 提出的建议：xxx

### 描述：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by Bouncysig18** [comment]
不对存在和不存在的tag十分混乱，都会显示真实存在和不存在的影片

**Comment by hitchao** [comment]
版本 [Jvedio-5.4](https://github.com/hitchao/Jvedio/releases/tag/5.4) 已修复
