### ISSUE TITLE
能一起刮削全部的影片吗？只能一部一部点同步？

### ISSUE THREAD

**Issue by jkwtbmyz** [hitchao/Jvedio#244]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议
rt，影库经常修改、挪来挪去、大批量删减，有没有刮削全部影片的功能？只能一部一部点“同步信息”吗？

- 出现问题的版本：（如5.0.0.0）
- 电脑系统：（如 win 10）
- 提出的建议：xxx

### 描述：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by hitchao** [comment]
空白处右键全选

**Comment by jkwtbmyz** [comment]
> 空白处右键全选

谢谢！“选中\取消当前页”倒是可以改成更直白的说法，哪怕就叫“全选”呢
另外，滚轮滚一次下滑的行数可否弄多一点，现在有点滑不动，只能用较小的影片图标，这样又看得不爽了

**Comment by jkwtbmyz** [comment]
> 空白处右键全选

“删除不存在影片”位置能否放在第0层？或者启动自动执行，就跟启动自动扫描一样；
同时怎么总是提示“需清空xxx任务”，即使我刚打开软件，也没有其他任务，干脆这个功能执行的时候自动停止其他任务吧，还需要手动关闭，况且现在也找不到要关闭啥

**Comment by jkwtbmyz** [comment]
> 空白处右键全选

右下角的通知，比如删除视频弹出的通知，能让他过几秒自动消失不？现在要手动关闭
或者换到其他不遮挡影片或者下一页按钮的位置

**Comment by hitchao** [comment]
右键清空就行

**Comment by jkwtbmyz** [comment]
> 右键清空就行

谢谢，早就该来感谢了，提交问题之后的下一个版本，很多建议都实装了
