### ISSUE TITLE
actor图片无法读取，显示“由于当前图片资源文相对于影片，因此该页面不显示头像”

### ISSUE THREAD

**Issue by 18371097369** [hitchao/Jvedio#245]
版本5.0
系统：Win11
问题描述：演员图片无论是在“选项-图片-相对于影片路径-演员头像”里设置好路径，还是根据wiki里提到的把演员图片放在Actresses文件夹下都无法读取，均显示“由于当前图片资源文相对于影片，因此该页面不显示头像”。语句似乎不太通，我也不太懂。

![搜狗截图20230103150252](https://user-images.githubusercontent.com/39733846/210313187-66a69107-4ebd-4406-bd04-2bca92538cf1.png)

麻烦看到可以帮忙解决一下，非常感谢！

**Comment by hitchao** [comment]
其实就是设置-图片路径，里面选择了相对于影片
这个图片路径下，由于不知道演员头像名字是什么，所以就不显示演员头像

**Comment by PhoenixNumber1** [comment]
> 其实就是设置-图片路径，里面选择了相对于影片 这个图片路径下，由于不知道演员头像名字是什么，所以就不显示演员头像

那如果设置相对于影片，是不是无法设置演员图片？

**Comment by hitchao** [comment]
> > 其实就是设置-图片路径，里面选择了相对于影片 这个图片路径下，由于不知道演员头像名字是什么，所以就不显示演员头像
> 
> 那如果设置相对于影片，是不是无法设置演员图片？

是的

**Comment by PhoenixNumber1** [comment]
还有一个问题想咨询一下，软件中的彩色标记是刮削后自动生成的吗？能不能自定义，以及自己给影片进行标记分类？
我找了半天没找到该怎么搞

**Comment by hitchao** [comment]
> 还有一个问题想咨询一下，软件中的彩色标记是刮削后自动生成的吗？能不能自定义，以及自己给影片进行标记分类？
> 我找了半天没找到该怎么搞

可以自定义，左边侧边栏点加号就可以
