### ISSUE TITLE
获取bus刮削器重启后报错

### ISSUE THREAD

**Issue by midaswakuwaku** [hitchao/Jvedio#246]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：5.0.0.0
- 电脑系统： win 10
### 描述：

获取bus刮削器后重启显示2023-01-04 18:50:52.834 => [Warning] 公告解析错误 
2023-01-04 18:52:13.623 => [Warning] [DispatcherUnhandledException] Jvedio 出现了一些问题，将退出 
但fc2刮削器可以正常获取

### 日志文件：

[2023/1/4 18:51:18]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Mapper\BaseMapper\BaseMapper.cs 方法: ExecuteNonQuery 行数: 37

[2023/1/4 18:52:13]
[Message] 无法加载一个或多个请求的类型。有关更多信息，请检索 LoaderExceptions 属性。
[StackTrace] 
 文件: \Jvedio-WPF\Jvedio\Core\Plugins\Crawler\CrawlerManager.cs 方法: GetPluginData 行数: 78
文件: \Jvedio-WPF\Jvedio\Core\Plugins\Crawler\CrawlerManager.cs 方法: LoadAllCrawlers 行数: 38
文件: \Jvedio-WPF\Jvedio\WindowStartUp.xaml.cs 方法: MoveNext 行数: 102

**Comment by hitchao** [comment]
更新到最新版本即可

**Comment by midaswakuwaku** [comment]
自动更新一直请求超时，我是直接下载的十月7日的版本难道不一样吗...

**Comment by hitchao** [comment]
> 自动更新一直请求超时，我是直接下载的十月7日的版本难道不一样吗...

不一样，自动更新是我前几天更新的，但是10.7的压缩包不是最新的，如果超时需要配置一下代理

**Comment by midaswakuwaku** [comment]
方便发我一份吗729511846@qq.com，不太想整个代理，感谢

**Comment by midaswakuwaku** [comment]
非常感谢
