### ISSUE TITLE
建议在所有视频里增加一个子文件用以分别不同文件夹的电影

### ISSUE THREAD

**Issue by xiaoxuan1991** [hitchao/Jvedio#247]
建议在所有视频里增加一个子文件用以分别不同文件夹的电影目录,我电影比较多2000多部,是分类存储在不同的文件夹里的,全部混在一起了
列如:扫描时文件时两个目录D:\电影1   D:\电影2 .  全部扫描到我的视频里,
我的电影
--电影1文件夹
--电影2文件夹

**Comment by hitchao** [comment]
可以给每个库绑定文件夹，然后勾选启动后扫描
