### ISSUE TITLE
更新报错

### ISSUE THREAD

**Issue by 1462168380** [hitchao/Jvedio#248]
### 反馈/建议

- 出现问题的版本：（5.0.0.0）
- 电脑系统：（win 10）

### 描述：
![image](https://user-images.githubusercontent.com/122136612/211128253-c89fe8a3-aa1b-4dee-a483-e0cf4e09700e.png)

**Comment by hitchao** [comment]
官网下载即可

**Comment by 1462168380** [comment]
官网最新不是10月7日的么？
