### ISSUE TITLE
已经有的nfo无法导入

### ISSUE THREAD

**Issue by m8250** [hitchao/Jvedio#25]
自己刮削的nfo文件无法导入
日志如下：

-----【2020/11/27 18:52:22】NFO扫描-----
扫描出 => 332  个 
成功导入 0 个

**Comment by hitchao** [comment]
请提供一下 NFO 文件

**Comment by m8250** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hitchao/Jvedio"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 晚上9:03
收件人:&nbsp;"hitchao/Jvedio"<Jvedio@noreply.github.com&gt;;
抄送:&nbsp;"D e v i l。"<yhy947@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hitchao/Jvedio] 已经有的nfo无法导入 (#25)





 
请提供一下 NFO 文件
