### ISSUE TITLE
可否在5.0新版本的后续更新中加入4.6的 右键去除车牌两个0的功能

### ISSUE THREAD

**Issue by DMyouass** [hitchao/Jvedio#251]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议
![YCBEM8 %Z{R7OIGO70M@%KN](https://user-images.githubusercontent.com/123372607/214029009-76e5d8fb-be2c-4e4b-ab5f-0e9813956844.png)

- 出现问题的版本：（如5.0.0.0）
- 电脑系统：（如 win 10）
- 提出的建议：xxx

### 描述：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by hitchao** [comment]
版本 [Jvedio-5.4](https://github.com/hitchao/Jvedio/releases/tag/5.4) 已修复
