### ISSUE TITLE
FC2插件下载后 重启后还是未下载状态

### ISSUE THREAD

**Issue by mygit-hripng** [hitchao/Jvedio#252]
- 出现问题的版本：（如5.1.0.0）
- 电脑系统：（如 win 11）

[2023/2/5 18:07:19]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/2/5 18:07:20]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/2/5 18:07:20]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/2/5 18:14:05]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/2/5 18:14:05]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/2/5 18:14:05]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/2/5 18:15:22]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/2/5 18:15:22]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/2/5 18:15:22]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/2/5 18:15:22]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/2/5 18:16:29]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/2/5 18:16:29]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/2/5 18:16:29]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/2/5 18:16:29]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/2/5 18:18:32]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/2/5 18:18:32]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/2/5 18:18:32]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/2/5 18:18:32]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/2/5 18:19:13]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/2/5 18:19:13]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/2/5 18:19:13]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/2/5 18:19:13]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/2/5 18:19:37]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/2/5 18:19:37]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/2/5 18:19:37]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/2/5 18:19:38]
[Message] 无法识别的 AbstractConfig
[StackTrace]

**Comment by hitchao** [comment]
这个插件目前暂时不可用

**Comment by hitchao** [comment]
5.2 已修复
