### ISSUE TITLE
5.1版本 怎么让ABC分段视频默认只显示一个视频

### ISSUE THREAD

**Issue by spartawhy117** [hitchao/Jvedio#256]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

- 出现问题的版本：5.1
- 电脑系统：win11
- 提出的建议：xxx

我单独去plugin的仓库下载了插件，但是刮削器这边还是灰色的，新增按钮也完全点击不了。这个要怎么解决？

**Comment by spartawhy117** [comment]
我知道了，要先创建仓库之后，才能在仓库里面下载插件使用，这个逻辑还有点怪

**Comment by hitchao** [comment]
这个我还没弄，周末我弄一下

**Comment by spartawhy117** [comment]
> 这个我还没弄，周末我弄一下

现在还有一个比较大的影响体验的问题就是排序目前好像不稳定，选择按发行日期排序，每次点击结果都不一致

**Comment by hitchao** [comment]
5.2 已修复
