### ISSUE TITLE
5.1同步信息 刮削器为何显示未启用 如何启用刮削

### ISSUE THREAD

**Issue by 1111111222233** [hitchao/Jvedio#257]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：（如5.0.0.0）
- 电脑系统：（如 win 10）
- 提出的建议：xxx

### 描述：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by Buffnada** [comment]
先去插件里安装bus  设置bus网址 重启软件    还不懂去看看帮助信息

**Comment by hitchao** [comment]
5.2 已修复
