### ISSUE TITLE
安装刮削重启程序，报错，辛苦帮助解决

### ISSUE THREAD

**Issue by heiha9898** [hitchao/Jvedio#258]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：5.1
- 电脑系统：win10
- 提出的建议：希望解决，谢谢

### 描述：

> 添加刮削就这样了，上个版本bus的还能用，f2的报错，这个版本一个都用不了了
我的资源都在移动硬盘中，是不是这个问题，如果能解决就太感谢了，4.x的版本都正常，5.x开始安装刮削插件重新打开就报错

详细说明前因后果、操作步骤。

### 日志文件：

>System.TypeInitializationException: “JvedioLib.Security.Encrypt”的类型初始值设定项引发异常。 ---> System.IO.FileLoadException: 未能加载文件或程序集“file:///C:\Users\JR\Downloads\Jvedio-5.1\JvedioLib.dll”或它的某一个依赖项。不支持操作。 (异常来自 HRESULT:0x80131515) ---> System.NotSupportedException: 尝试从一个网络位置加载程序集，在早期版本的 .NET Framework 中，这会导致对该程序集进行沙盒处理。此发行版的 .NET Framework 默认情况下不启用 CAS 策略，因此，此加载可能会很危险。如果此加载不是要对程序集进行沙盒处理，请启用 loadFromRemoteSources 开关。有关详细信息，请参见 http://go.microsoft.com/fwlink/?LinkId=155569。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   在 System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   在 System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   在 System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   在 System.Reflection.Assembly.LoadFrom(String assemblyFile)
   在 JvedioLib.Security.Encrypt..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 JvedioLib.Security.Encrypt.GetFileMD5(String filename)
   在 Jvedio.Core.Plugins.Crawler.CrawlerManager.LoadAllCrawlers()
   在 Jvedio.WindowStartUp.<Window_Loaded>d__17.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by heiha9898** [comment]
好像和我资源无关，不用之前的资源，新版本新建库没有任何资源的情况下安装bus刮削重启后就弹这个异常了

**Comment by QZQ-QSQ** [comment]
+1

**Comment by bobipoppy** [comment]
@hitchao 看下这个问题呗如何解决呢？我也遇到了。
![捕获](https://user-images.githubusercontent.com/50575997/224532699-8e42f7cb-8b43-4d9f-93d9-b2516347b260.PNG)

**Comment by hitchao** [comment]
5.2 已修复
