### ISSUE TITLE
导入NFO发行日期错误

### ISSUE THREAD

**Issue by kenz1025** [hitchao/Jvedio#26]
nfo由JAVMovieScraper刮削，导入后所有的发行日期变成了0001-01-01，其他的字段都正常
btw，导入nfo经常中途卡死

**Comment by hitchao** [comment]
请提供一下 NFO文件

**Comment by kenz1025** [comment]
**重新建库导入了一下，同时导入的目录里大概有十分之一的NFO导入后能显示正确发行日期，剩下90%左右都是0001-01-01
以下是显示错误的NFO内容：**

<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<movie>
  <title>家事代行xxxxx</title>
  <originaltitle>家事代行xxxxx</originaltitle>
  <sorttitle></sorttitle>
  <set>ピタパンxxxxxxxxx</set>
  <year>2019</year>
  <top250></top250>
  <trailer></trailer>
  <votes>7</votes>
  <rating>8.9</rating>
  <outline></outline>
  <plot>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</plot>
  <tagline></tagline>
  <runtime>240</runtime>
  <releasedate>2019-06-07</releasedate>
  <studio>ディープス</studio>
  <thumb>https://xxxxxxxxxx/mono/movie/axx/dvdms406so/dvdms406sopl.jpg</thumb>
  <fanart>
    <thumb>https://xxxxxxxxxx/mono/movie/axx/dvdms406so/dvdms406sopl.jpg</thumb>
  </fanart>
  <mpaa>XXX</mpaa>
  <id>DVDMS-406</id>
  <genre>中XX</genre>
  <genre>素XX</genre>
  <genre>人XX</genre>
   <actor>
    <name>水xxxx</name>
    <role></role>
    <thumb></thumb>
  </actor>
  <actor>
    <name>かxxxxx</name>
    <role></role>
    <thumb></thumb>
  </actor>
  <actor>
    <name>大xxxxxx</name>
    <role></role>
    <thumb></thumb>
  </actor>
  <director>ナxxxxxxxx</director>
</movie>


**以下是可以正确显示日期的NFO内容：**
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<movie>
  <title>先輩xxxxxxxxx</title>
  <originaltitle>先輩xxxxxxxx</originaltitle>
  <sorttitle></sorttitle>
  <set>生xxxxxx</set>
  <year>2019</year>
  <top250></top250>
  <trailer></trailer>
  <votes>5</votes>
  <rating>9.6</rating>
  <outline></outline>
  <plot>先輩xxxxxxxxxxxxx</plot>
  <tagline></tagline>
  <runtime>150</runtime>
  <releasedate>2019-03-07</releasedate>
  <studio>DEEP’S</studio>
  <thumb>https://xxxxxxxx/mono/movie/adxxx/dvdms372so/dvdms372sopl.jpg</thumb>
  <fanart>
    <thumb>https://xxxxxxxxx/mono/movie/adzzz/dvdms372so/dvdms372sopl.jpg</thumb>
  </fanart>
  <mpaa>XXX</mpaa>
  <id>DVDMS-372SO</id>
  <genre>巨xxx</genre>
  <genre>素xxx</genre>
  <genre>寝xxx</genre>
  <actor>
    <name>八xxx</name>
    <thumb></thumb>
  </actor>
  <director>ルxxxx</director>
</movie>

**还有搜索经常直接崩溃，系统win10x64，程序挂sockscap64代理运行**

**Comment by kenz1025** [comment]
重新建库导入了一下，同时导入的目录里大概有十分之一的NFO导入后能显示正确发行日期，剩下90%左右都是0001-01-01
以下是显示错误的NFO：

http://176.122.190.118:8888/down/UystMMY25bVV

以下是可以正确显示日期的NFO：
http://176.122.190.118:8888/down/KkZSh6BkCmI0

还有搜索经常直接程序崩溃，系统win10x64，程序挂sockscap64代理运行

**Comment by hitchao** [comment]
已修复
