### ISSUE TITLE
关于源文件在同步结束后没有重命名

### ISSUE THREAD

**Issue by chenryace** [hitchao/Jvedio#261]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**
# 感谢H大多年孜孜不倦的努力，14年就知道这个软件，后来口味变了就没用了。不过最近又想梳理青春，又用了起来。
### 反馈/建议
同步信息时，个别车牌无法匹配演员，导致识别时间过长，从而导致系统崩溃，这个没放在日志中。

- 出现问题的版本：（如5.1.0.0）
- 电脑系统：（如 win 10）

### 描述：

在设置那里已经配置好了。但右键—>全部资源—>同步信息，同步完所有信息后，源文件却没有重新命名，不知道是不是要下个renamer才行。但我之前好像是不需要的。

详细说明前因后果、操作步骤。

#### 这个是后段的log。
[2023/2/19 21:45:37]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 21:48:31]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 21:48:36]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 21:48:36]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 21:55:37]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 21:58:34]
[Message] 调用的目标发生了异常。
[StackTrace] 
 
[2023/2/19 21:58:38]
[Message] 调用的目标发生了异常。
[StackTrace] 
 
[2023/2/19 21:58:38]
[Message] 调用的目标发生了异常。
[StackTrace] 
 
[2023/2/19 21:58:39]
[Message] 调用的目标发生了异常。
[StackTrace] 
 
[2023/2/19 21:58:58]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 21:59:53]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 22:00:01]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 22:08:17]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 22:09:52]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 22:11:23]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 22:12:41]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 22:13:06]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 22:13:29]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 22:15:19]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 22:21:30]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 22:26:48]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 22:27:13]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 22:28:06]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 22:28:08]
[Message] 未通过等待任务或访问任务的 Exception 属性观察到任务的异常。因此，终结器线程重新引发了未观察到的异常。
[StackTrace] 
 
[2023/2/19 23:15:49]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 23:28:48]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/2/19 23:30:47]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by hitchao** [comment]
重命名需要右键-重命名，另外 jvedio 我在19 年才开发的……
