### ISSUE TITLE
win11 扫描 ts 文件崩溃

### ISSUE THREAD

**Issue by the55555day** [hitchao/Jvedio#262]
添加库，导入视频就会崩溃。后来测试，只要截图就会崩溃，已经更换了好几个版本的 ffmpeg.exe 都如此。

不止 ts 文件， mp4 文件也不行

**Comment by mashaz** [comment]
我也遇到，看报错是缺少dll，把```https://github.com/hitchao/Jvedio/blob/master/Jvedio-WPF/Jvedio/Reference/MediaInfo.dll```下载放到jvedeio根目录下解决了

**Comment by hitchao** [comment]
win11会对dll做安全检验，包括刮削器也是

解决方法也简单
对着刮削器或者其他dll，右键，属性，找到对应的安全选项，解除限制即可

**Comment by hitchao** [comment]
win11会对dll做安全检验，包括刮削器也是

解决方法也简单
对着刮削器或者其他dll，右键，属性，找到对应的安全选项，解除限制即可

**Comment by hitchao** [comment]
win11会对dll做安全检验，包括刮削器也是

解决方法也简单
对着刮削器或者其他dll，右键，属性，找到对应的安全选项，解除限制即可

**Comment by hitchao** [comment]
5.2 已修复
