### ISSUE TITLE
刮削插件报错

### ISSUE THREAD

**Issue by yang201212** [hitchao/Jvedio#263]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：（如5.0.0.0）
- 电脑系统：（如 win 10）
- 提出的建议：xxx

### 描述：
DLL加载失败 => E:\壁纸\密咪\Jvedio-5.1\plugins\crawlers\bus\BusCrawler.dll, reason: classType == null || instance == null
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。

### 日志文件：
[2023-03-12 周日 23:48:42]
[Message] 未找到类型“Jvedio.Crawler.BusCrawler”上的构造函数。
[StackTrace] 
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by hitchao** [comment]
5.2 已修复
