### ISSUE TITLE
win11刮削插件报错

### ISSUE THREAD

**Issue by lovegood77** [hitchao/Jvedio#264]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：5.1
- 电脑系统：win11
- 提出的建议：之前在其他提问中看到过大佬给的解决方案是右键dll文件-属性-解除限制，但是实际操作后并没有在win11系统的右键属性中找到解除限制，也无法绕过win11的dll安全检查，大佬求解决方法！

### 描述：

DLL加载失败 => G:\大书库\Jvedio-5.1\plugins\crawlers\bus\BusCrawler.dll, reason: classType == null || instance == null

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by hitchao** [comment]
5.2 已修复
