### ISSUE TITLE
请求大佬们帮忙给个获取请求头的小教程！！！谢谢！

### ISSUE THREAD

**Issue by layerpagex** [hitchao/Jvedio#266]
我是新人，好不容易使用上这个软件，可是在DB刮削时，不会获取请求头，我已经使用了edge的F12，在请求标头下，无论是从:authority复制到底，还是从只复制cookie:项目内内容，都不可以通过。目前DB可以正常访问。
请求大佬告知如何复制！

**Comment by hitchao** [comment]
参考：https://github.com/hitchao/Jvedio/wiki/05_Headers
