### ISSUE TITLE
希望能通过这个软件学习一些VS的开发经验

### ISSUE THREAD

**Issue by david-onec** [hitchao/Jvedio#268]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议
最近刚好有管理本地视频的需求，发现这一神器，但发现软件还是存在很多不完善的地方。
之前玩过C#和Web的开发，希望能借此了解桌面的开发，如果作者愿意，能否加一下开发群：19118662，谢谢了。

- 出现问题的版本：（如5.0.0.0）
- 电脑系统：（如 win 10）
- 提出的建议：xxx

### 描述：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by hitchao** [comment]
非常欢迎！
但是QQ已经停用了，如果对 Jvedio 开发感兴趣，欢迎加入 tg 群，https://t.me/code_develop

**Comment by david-onec** [comment]
真遗憾，试了国内的手机一直收不到验证码



---原始邮件---
发件人: "Ma ***@***.***&gt;
发送时间: 2023年3月22日(周三) 晚上8:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hitchao/Jvedio] 希望能通过这个软件学习一些VS的开发经验 (Issue #268)




 
非常欢迎！
 但是QQ已经停用了，如果对 Jvedio 开发感兴趣，欢迎加入 tg 群，https://t.me/code_develop

**Comment by hitchao** [comment]
是的，国内手机用不了的，只能申请一个 google voice 号码

**Comment by david-onec** [comment]
google voiceb也不支持所在地区，能否加个Q？



---原始邮件---
发件人: "Ma ***@***.***&gt;
发送时间: 2023年3月26日(周日) 晚上11:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hitchao/Jvedio] 希望能通过这个软件学习一些VS的开发经验 (Issue #268)




 
是的，国内手机用不了的，只能申请一个 google voice 号码

**Comment by hitchao** [comment]
可以加我 discard 账号：chao#9575
