### ISSUE TITLE
5.2版本覆盖更新后提示软件发生了异常

### ISSUE THREAD

**Issue by WengQW** [hitchao/Jvedio#273]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：5.2
- 电脑系统：win 10

### 描述：
5.2版本覆盖更新后提示软件发生了异常，打开影视库就异常闪退

详细说明前因后果、操作步骤。

### 日志文件：

System.TypeInitializationException: “SuperUtils.WPF.VisualTools.VisualHelper”的类型初始值设定项引发异常。 ---> System.ArgumentException: 已添加了具有相同键的项。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   在 SuperUtils.WPF.VisualTools.VisualHelper.GetSystemFonts()
   在 SuperUtils.WPF.VisualTools.VisualHelper..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 SuperUtils.WPF.VisualTools.VisualHelper.HexStringToBrush(String hexString)
   在 SuperControls.Style.Plugin.Themes.Theme.GetViewBrush()
   在 SuperControls.Style.Plugin.Themes.ThemeManager.LoadAllThemes()
   在 SuperControls.Style.ThemeSelector.InitThemes()
   在 Jvedio.Main.InitThemeSelector()
   在 Jvedio.Main.Window_ContentRendered(Object sender, EventArgs e)
   在 System.EventHandler.Invoke(Object sender, EventArgs e)
   在 System.Windows.Window.OnContentRendered(EventArgs e)
   在 System.Windows.Window.<PostContentRendered>b__202_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by 192122588** [comment]
+1

**Comment by hitchao** [comment]
重新上传了，试试看
