### ISSUE TITLE
5.2版本打开后程序异常

### ISSUE THREAD

**Issue by zh-xc** [hitchao/Jvedio#275]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：5.2
- 电脑系统： win 10

### 描述：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。
5.2版本不管是更新还是重新下载，程序打开后都是显示程序异常

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

System.TypeInitializationException: “SuperUtils.WPF.VisualTools.VisualHelper”的类型初始值设定项引发异常。 ---> System.ArgumentException: 已添加了具有相同键的项。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   在 SuperUtils.WPF.VisualTools.VisualHelper.GetSystemFonts()
   在 SuperUtils.WPF.VisualTools.VisualHelper..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 SuperUtils.WPF.VisualTools.VisualHelper.HexStringToBrush(String hexString)
   在 SuperControls.Style.Plugin.Themes.Theme.GetViewBrush()
   在 SuperControls.Style.Plugin.Themes.ThemeManager.LoadAllThemes()
   在 SuperControls.Style.ThemeSelector.InitThemes()
   在 SuperControls.Style.Windows.Dialog_SetSkinLang.InitThemes()
   在 Jvedio.WindowStartUp.<Window_Loaded>d__17.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by hitchao** [comment]
重新上传了，试试看

**Comment by zh-xc** [comment]
问题解决
