### ISSUE TITLE
5.2版本导入视频无法用，刮削功能无法用

### ISSUE THREAD

**Issue by nixiwoha** [hitchao/Jvedio#276]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：5.2
- 电脑系统：（如 win 10）
- 提出的建议：导入视频无法用，刮削功能无法用

### 描述：
导入视频提示的导入数是0
刮削器无法使用，显示“无对应刮削器刮削”

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。
从旧版本升级和下载新版本解压两种方式都有问题，其中下载5.2新版本解压后新建库导入视频就出现这个问题，导入0

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by hitchao** [comment]
win10还是 11

**Comment by hitchao** [comment]
估计是权限问题

**Comment by nixiwoha** [comment]
如何解决这问题，我用管理员权限打开还是这样

**Comment by hitchao** [comment]
扫描大小设置为 0 MB，然后选择一个 mp4 的视频，直接拖到软件里，看看显示什么

**Comment by nixiwoha** [comment]
扫描大小设置0就可以了

**Comment by nixiwoha** [comment]
用之前的5.1扫描大小设置0 正常了，切换到5.2版本大小设成0拖进来还是显示导入0

**Comment by hotqi** [comment]
“无对应刮削器刮削”是选项-插件 还有个【是否启用】的选项，打开就能同步了。

**Comment by nixiwoha** [comment]
谢谢 ，5.1版本目前正常了，用5.1的

**Comment by LiuJack** [comment]
我下载的5.2也无法导入，win10，.net4.7.2已装。尝试自己build出来了也是无法导入，跟踪错误在jvediolib.Identify是空的，看了下估计是dll导入问题，没继续跟了。不过我另外一台电脑build出来却是可以导入的。。。

**Comment by hitchao** [comment]
> 我下载的5.2也无法导入，win10，.net4.7.2已装。尝试自己build出来了也是无法导入，跟踪错误在jvediolib.Identify是空的，看了下估计是dll导入问题，没继续跟了。不过我另外一台电脑build出来却是可以导入的。。。

JvedioLib.dll ，右键解除限制
