### ISSUE TITLE
5.2版本无法刮削了

### ISSUE THREAD

**Issue by wu1987112** [hitchao/Jvedio#277]
![image](https://user-images.githubusercontent.com/38690969/227988756-479efe91-6914-4ba4-876d-415262d043e9.png)

![image](https://user-images.githubusercontent.com/38690969/227988883-e8aa55a4-f5a5-4820-8d21-659454592633.png)

作者好好看看吧··怎么解决刮削问题。

**Comment by hitchao** [comment]
刮不动是什么原因

**Comment by wu1987112** [comment]
> 刮不动是什么原因

不知道啊..就是不动，但是我发现用新的独立5.2可以刮动，另外求救... 我用新的库把我原来的库覆盖了..如何找回原来的库。大库里有一堆小库

**Comment by wu1987112** [comment]
> 刮不动是什么原因

而且同步完成也没有同步图片，只是同步了信息

**Comment by hitchao** [comment]
> > 刮不动是什么原因
> 
> 不知道啊..就是不动，但是我发现用新的独立5.2可以刮动，另外求救... 我用新的库把我原来的库覆盖了..如何找回原来的库。大库里有一堆小库

都在 data 目录里，backup 目录也有

**Comment by hitchao** [comment]
> > 刮不动是什么原因
> 
> 而且同步完成也没有同步图片，只是同步了信息

网络问题，下载图片慢

**Comment by spartawhy117** [comment]
> 刮不动是什么原因
[2023-03-28 01:32:36.934] [Info] 下载中...
[2023-03-28 01:32:36.937] [Info] 1. 开始同步信息
[2023-03-28 01:32:36.946] [Erro] 调用线程无法访问此对象，因为另一个线程拥有该对象。
[2023-03-28 01:32:36.946] [Info] Cancel
[2023-03-28 01:32:36.946] [Info] 9ms

5.1升级，没有单独下载新版本是这样的，配置好 插件和header，搜刮的时候说调用线程无法访问此对象

**Comment by JadeButterfly** [comment]
实测应用内升级无法刮削如题主所示，单独下载升级成功刮削。

**Comment by Buffnada** [comment]
我先下载5.2 然后复制到5.1文件夹覆盖也有这些问题 已解决
1.插件里删除bus插件 重启软件
2.重新安装bus插件 设置网站 可以刮削了
