### ISSUE TITLE
Jvedio5.2无法正常启用同步预览图功能

### ISSUE THREAD

**Issue by JadeButterfly** [hitchao/Jvedio#278]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

Jvedio 5.2

### 描述：
同步选项勾选预览图并重启后，仍无法正常同步。
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)
![image](https://user-images.githubusercontent.com/50535821/228031455-8109ba2e-bf49-4bfb-932a-3f6f8342ad38.png)
![image](https://user-images.githubusercontent.com/50535821/228032430-81b18933-7d4e-4fce-8d94-7981ff9dafb0.png)

**Comment by YiCarlos** [comment]
同样的问题，请问解决了吗？

**Comment by ClaptrapCL4P** [comment]
一样的，5.3.1还是这个bug

**Comment by hitchao** [comment]
版本 [Jvedio-5.4](https://github.com/hitchao/Jvedio/releases/tag/5.4) 已修复
