### ISSUE TITLE
单独添加识别码，然后 把视频拖入文件位置，既打不开文件也不能定位文件

### ISSUE THREAD

**Issue by wujie985432** [hitchao/Jvedio#282]
单独添加识别码，然后 把视频拖入文件位置，既打不开文件也不能定位文件
![eaa3cc2c0698f584964182c165c6d310_228277513-01d2d1aa-ff47-4f5c-90c0-187e6b07b6be](https://user-images.githubusercontent.com/80050604/228459520-fa7f0fb0-09af-4f2d-83fb-3ce1dceb483e.jpg)

**Comment by hitchao** [comment]
版本 [Jvedio-5.4](https://github.com/hitchao/Jvedio/releases/tag/5.4) 已修复
