### ISSUE TITLE
昨天DB还能用，今天测试就无法通过了，怎么操作也不行咋回事？

### ISSUE THREAD

**Issue by wu1987112** [hitchao/Jvedio#284]
![image](https://user-images.githubusercontent.com/38690969/229264494-2589b677-788c-48f5-85b6-b31ea660bc7d.png)

**Comment by wu1987112** [comment]
地址是可以访问的 Headers全部重新填写也不行

**Comment by Buffnada** [comment]
那就换个地址啊javdb008.com

**Comment by wu1987112** [comment]
> 那就换个地址啊javdb008.com

也不行.都测试超时或无效 郁闷了·

**Comment by Buffnada** [comment]
把插件删了 重启软件  再安装一遍插件

**Comment by wu1987112** [comment]
> 把插件删了 重启软件 再安装一遍插件

还是不行，你那边能通过测试嘛？

**Comment by Buffnada** [comment]
5.2 可以刮削  你下载新的5.2解压覆盖原本文件夹试试
