### ISSUE TITLE
将Jvedio装移动硬盘里，换了个PC，打开软件一切都是初始化的，请问怎么解决？

### ISSUE THREAD

**Issue by Adibbbaddy** [hitchao/Jvedio#293]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

小白请教。视频和Jvedio都装在一个移动硬盘里，且在一台PC上已经设置好了库和其他影片信息，然后在把移动硬盘接在另一台PC上打开Jvedio，发现默认在新电脑上打开一切都是初始化的，原来的库信息怎么打开呢？影片都是一样的路径。请教下怎么解决呀？

**Comment by hitchao** [comment]
数据都是存在 Jvedio/data/你的用户名/ 目录里，看看是不是用户名变了
