### ISSUE TITLE
所有插件节点jav\bus\db\等等全部都超时我也是醉了这5.2能不能用了啊？

### ISSUE THREAD

**Issue by wu1987112** [hitchao/Jvedio#294]
太无语了啊。。

**Comment by DreamingChao** [comment]
你这啥态度，作者这软件是免费的，出点问题很正常，好像欠你一样，爱用不用

**Comment by wu1987112** [comment]
> 你这啥态度，作者这软件是免费的，出点问题很正常，好像欠你一样，爱用不用

来来来你什么态度给我展示一下？ 这不是正常反馈？ 我看看你怎么跪舔的·

**Comment by DreamingChao** [comment]
你这叫正常反馈？有问题就客观陈述就是了，还夹杂着“我也是醉了”“太无语了啊”等抱怨词汇，这叫正常反馈？

**Comment by DreamingChao** [comment]
> > 你这啥态度，作者这软件是免费的，出点问题很正常，好像欠你一样，爱用不用
> 
> 来来来你什么态度给我展示一下？ 这不是正常反馈？ 我看看你怎么跪舔的·
你这叫正常反馈？有问题就客观陈述就是了，还夹杂着“我也是醉了”“太无语了啊”等抱怨词汇，这叫正常反馈？

**Comment by DreamingChao** [comment]
> > 你这啥态度，作者这软件是免费的，出点问题很正常，好像欠你一样，爱用不用
> 
> 来来来你什么态度给我展示一下？ 这不是正常反馈？ 我看看你怎么跪舔的·

你这叫正常反馈？有问题就客观陈述就是了，还夹杂着“我也是醉了”“太无语了啊”等抱怨词汇，这叫正常反馈？
