### ISSUE TITLE
几个新版本小问题

### ISSUE THREAD

**Issue by 10929485** [hitchao/Jvedio#299]
1，图书馆的刮削器有几率串行。把信息倒到隔壁片子上
2、原有nfo不读取，拖进去也没用，重新刮削才显示
3、部分片子全盘扫描后，按大小排序或前或后有几率产生一个残影（只有片名没有图片和番号）删了残影后本体也会消失
4、一个片子的演员有几率出现俩个一模一样的信息但不互通，我没敢删，跟上条一样本体消失可就坏了（奇奇怪怪的BUG）
5、扫描添加一个以上的盘大几率崩溃
6、像498DDH-063这种格式的片子，导入会保留前三个数字，但没用得手动删

**Comment by hitchao** [comment]
版本 [Jvedio-5.4](https://github.com/hitchao/Jvedio/releases/tag/5.4) 已修复
