### ISSUE TITLE
大佬，可以写一个Mac版吗

### ISSUE THREAD

**Issue by xljhd** [hitchao/Jvedio#3]

**Comment by hitchao** [comment]
可能不太行呢，不过考虑写个web的


 
---原始邮件---
发件人: "嘎嘎嘎"<notifications@github.com&gt;
发送时间: 2020年1月6日(星期一) 晚上8:20
收件人: "hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hitchao/Javedio-2.0] 大佬，可以写一个Mac版吗 (#3)

**Comment by xljhd** [comment]
web的也可以呀，辛苦辛苦





------------------ 原始邮件 ------------------
发件人: hitchao <notifications@github.com&gt;
发送时间: 2020年1月6日 22:18
收件人: hitchao/Javedio-2.0 <Javedio-2.0@noreply.github.com&gt;
抄送: 嘎嘎嘎 <728599123@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hitchao/Javedio-2.0] 大佬，可以写一个Mac版吗 (#3)



可能不太行呢，不过考虑写个web的 
 
 
   
 ---原始邮件--- 
 发件人: "嘎嘎嘎"<notifications@github.com&amp;gt; 
 发送时间: 2020年1月6日(星期一) 晚上8:20 
 收件人: "hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: [hitchao/Javedio-2.0] 大佬，可以写一个Mac版吗 (#3)

**Comment by victor-crypto** [comment]
web也行，辛苦大佬了，磕头了！

**Comment by hitchao** [comment]
最近再考虑做web版的------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;victor-wu.eth&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月30日(星期六) 凌晨1:53
收件人:&nbsp;&quot;hitchao/Jvedio&quot;<Jvedio@noreply.github.com&gt;;
抄送:&nbsp;&quot;hitchao&quot;<2415923016@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [hitchao/Jvedio] 大佬，可以写一个Mac版吗 (#3)

**Comment by xljhd** [comment]
大佬加油





------------------ 原始邮件 ------------------
发件人: hitchao <notifications@github.com&gt;
发送时间: 2020年5月30日 18:14
收件人: hitchao/Jvedio <Jvedio@noreply.github.com&gt;
抄送: 嘎嘎嘎 <728599123@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hitchao/Jvedio] 大佬，可以写一个Mac版吗 (#3)





 最近再考虑做web版的------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&amp;quot;victor-wu.eth&amp;quot;<notifications@github.com&amp;gt; 
 发送时间:&amp;nbsp;2020年5月30日(星期六) 凌晨1:53 
 收件人:&amp;nbsp;&amp;quot;hitchao/Jvedio&amp;quot;<Jvedio@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;hitchao&amp;quot;<2415923016@qq.com&amp;gt;;&amp;quot;Comment&amp;quot;<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [hitchao/Jvedio] 大佬，可以写一个Mac版吗 (#3)

**Comment by JamesDream87** [comment]
> 最近再考虑做web版的------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;victor-wu.eth&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年5月30日(星期六) 凌晨1:53 收件人:&nbsp;&quot;hitchao/Jvedio&quot;<Jvedio@noreply.github.com&gt;; 抄送:&nbsp;&quot;hitchao&quot;<2415923016@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [hitchao/Jvedio] 大佬，可以写一个Mac版吗 (#3)

了解一下electron，VSCode 也是用这个技术，写一套，可打包Mac，windows, Ubuntu。
