### ISSUE TITLE
影片信息同步偏移问题

### ISSUE THREAD

**Issue by JadeButterfly** [hitchao/Jvedio#303]
影片A和影片B相邻，影片B同步成功，影片A全部同步成影片B的信息(比如图片和简介)。
例如:
期待情况:
好汉歌-刘欢、性别男...
恋爱循环-花泽香菜、性别女...
实际情况:
好汉歌-花泽香菜、性别女...
恋爱循环-花泽香菜、性别女...
以上仅为举例，并非实际影片。
该问题长期多次出现。

**Comment by Buffnada** [comment]
确实有这问题   感觉是选一页对象太多同时同步导致的  但又不是每次都出问题，我一般是点进影片详情页删除所有照片出来再删除影片信息  开关软件 重新导入影片 同步

**Comment by JadeButterfly** [comment]
> 确实有这问题   感觉是选一页对象太多同时同步导致的  但又不是每次都出问题，我一般是点进影片详情页删除所有照片出来再删除影片信息  开关软件 重新导入影片 同步

我出错后单选同步也没法修正，即使删照片和信息后重启也是这样。

**Comment by hitchao** [comment]
最新版本已修复
