### ISSUE TITLE
程序异常

### ISSUE THREAD

**Issue by 37echo** [hitchao/Jvedio#309]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：5.0.0.0
- 电脑系统：win 10
- 提出的建议：

### 描述：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

打开软件就会弹出这个程序异常，点关闭，软件就直接退了

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 SuperControls.Style.Plugin.PluginMetaData.SetImagePath(PluginMetaData& data, String pluginDir)
   在 SuperControls.Style.Plugin.PluginMetaData.ParseByPath(String jsonPath)
   在 Jvedio.Core.Plugins.Crawler.CrawlerManager.GetPluginData(String dllPath)
   在 Jvedio.Core.Plugins.Crawler.CrawlerManager.Init(Boolean moveFile)
   在 Jvedio.WindowStartUp.<Window_Loaded>d__18.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
![屏幕截图 2023-06-10 232601](https://github.com/hitchao/Jvedio/assets/136182282/f1c75d3e-f2fc-4683-8fe9-99b979e8efcb)

**Comment by wujie985432** [comment]
子目录下不能有中文或放到根目录下

**Comment by 37echo** [comment]
> 

还是不行

**Comment by Antony0001** [comment]
插件重新安装

**Comment by hitchao** [comment]
版本 [Jvedio-5.4](https://github.com/hitchao/Jvedio/releases/tag/5.4) 已修复
