### ISSUE TITLE
5.3 版本多选删除文件异常

### ISSUE THREAD

**Issue by spartawhy117** [hitchao/Jvedio#312]
5.3.0 版本

多选删除文件不会删除库里的信息，然后点击影视库清理总会提示不满足条件

**Comment by spartawhy117** [comment]
另外还发现了，每次打开库，扫描不到目录里的新文件了

**Comment by hitchao** [comment]
需要在设置里，勾选删除文件时删除影片信息，扫描的时候需要设置最小文件大小
