### ISSUE TITLE
软件加载错误，只有在打开腾讯电脑管家后才能正常加载

### ISSUE THREAD

**Issue by nickwxx** [hitchao/Jvedio#315]
[2023/6/24 19:50:54]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 19:50:54]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 19:50:54]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 19:50:55]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 19:52:09]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 19:52:09]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 19:52:09]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 19:52:09]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 19:55:45]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 19:55:45]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 19:55:45]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 19:55:45]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 19:56:44]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 19:56:44]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 19:56:44]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 19:56:44]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 19:59:18]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 19:59:18]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 19:59:18]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 19:59:18]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 20:01:52]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 20:01:52]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 20:01:52]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 20:01:52]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 20:03:26]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 20:03:26]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 20:03:26]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 20:03:26]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 20:05:38]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 20:05:38]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 20:05:38]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 20:05:38]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 20:08:25]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 20:08:25]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 20:08:25]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 20:08:25]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 20:10:22]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 20:10:22]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 20:10:22]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 20:10:22]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 20:19:56]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 20:19:56]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 20:19:56]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 20:19:56]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 20:20:53]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 20:20:53]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 20:20:53]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 20:20:53]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 20:21:33]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 20:21:33]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 20:21:33]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 20:21:33]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 20:22:19]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 20:22:19]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 20:22:19]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 20:22:19]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 20:44:18]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 20:44:18]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 20:44:18]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 20:44:18]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 21:26:55]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 21:26:55]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 21:26:55]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 21:26:55]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 21:33:59]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 21:33:59]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 21:33:59]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 21:33:59]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 21:35:06]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 21:35:06]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 21:35:06]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 21:35:07]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 21:38:14]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 21:38:14]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 21:38:14]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 21:38:14]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 21:38:34]
[Message] SQL logic error
duplicate column name: PathExist
[StackTrace] 
 
[2023/6/24 21:38:34]
[Message] SQL logic error
duplicate column name: ImageUrl
[StackTrace] 
 
[2023/6/24 21:38:34]
[Message] SQL logic error
no such table: common_search_history
[StackTrace] 
 
[2023/6/24 21:38:34]
[Message] 无法识别的 AbstractConfig
[StackTrace] 
 
[2023/6/24 21:39:36]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/6/24 21:39:44]
[Message] bad parameter or other API misuse
database is locked
[StackTrace] 
 
[2023/6/24 21:39:44]
[Message] bad parameter or other API misuse
not an error
[StackTrace] 
 
[2023/6/24 21:41:13]
[Message] bad parameter or other API misuse
not an error
[StackTrace]

**Comment by kk77mgj** [comment]
没想到的问题，开电脑管家才能加载，确定不是Windows defender拦截了吗？
给的日志error都是SQL问题，我的日志里也有这些，不影响软件启动。

**Comment by hitchao** [comment]
估计是某个 dll 被 windows defender 拦截了
