### ISSUE TITLE
请添加4.6.11老版本的右键去除标题两个00的功能 因为DMM扒下来的资源车牌中会多两个00 导致无法刮削

### ISSUE THREAD

**Issue by DMYOU1111** [hitchao/Jvedio#316]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：（如5.0.0.0）
- 电脑系统：（如 win 10）
- 提出的建议：xxx

### 描述：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by DMYOU1111** [comment]
![Uploading 1.png…]()

**Comment by DMYOU1111** [comment]
![1](https://github.com/hitchao/Jvedio/assets/137811102/680c51c7-ce25-49df-b4ae-4cef44bd2236)

**Comment by hitchao** [comment]
版本 [Jvedio-5.4](https://github.com/hitchao/Jvedio/releases/tag/5.4) 已修复
