### ISSUE TITLE
5.3 无法添加分段视频

### ISSUE THREAD

**Issue by zzzzxcshuijiao** [hitchao/Jvedio#318]
5.3版本，点击视频-编辑-添加分段视频时，没有弹出文件资源管理器，而是文本输入框，将对应待添加的视频的路径填入后保存，再次打开编辑，信息并未保存

**Comment by hitchao** [comment]
刚修复，下载地址：[5.3.1](https://github.com/hitchao/Jvedio/releases/tag/5.3.1)
