### ISSUE TITLE
批量删除文件是会弹出每个文件的删除确认框，建议增加取消这个的选项或者取消这个提示框

### ISSUE THREAD

**Issue by xiaoxuan1991** [hitchao/Jvedio#319]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议
批量删除文件是会弹出每个文件的删除确认框，建议设置增加取消这个的选项或者取消这个提示框

**Comment by xiaoxuan1991** [comment]
我是PC运行软件，文件存储在NAS上的，电脑本地有删除确认提示取消的选择，但是对NAS的文件好像没有效果

**Comment by hitchao** [comment]
这个可能得设置一下nas的配置
