### ISSUE TITLE
发现一个BUG，不知道是不是数据库的问题

### ISSUE THREAD

**Issue by jackdanny77** [hitchao/Jvedio#324]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议
发现一个BUG，不知道是不是数据库的问题，开始用的时候用文件扫描只能扫描到12535个文件，再多就扫不出来了，试了很多次，也换了好几个版本（5.0 5.3 5.3.1）都是同样的问题，每次都是扫到一个文件就定住了。还有忘记说了一下，我扫的文件夹是用clouddrive2映射的115网盘，这个正常在电脑中显示打开都没有问题。想请大神帮忙解决一下

- 出现问题的版本：（如5.3.0.0）
- 电脑系统：（如 win 11）
- 提出的建议：xxx

### 描述：
发现一个BUG，不知道是不是数据库的问题，开始用的时候用文件扫描只能扫描到12535个文件，再多就扫不出来了，试了很多次，也换了好几个版本（5.0 5.3 5.3.1）都是同样的问题，每次都是扫到一个文件就定住了。还有忘记说了一下，我扫的文件夹是用clouddrive2映射的115网盘，这个正常在电脑中显示打开都没有问题。想请大神帮忙解决一下
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by hitchao** [comment]
这个应该已经修复了
