### ISSUE TITLE
提一个小建议，每页的影片数量希望可以自定义，多一点像4.6那样就很好用

### ISSUE THREAD

**Issue by kingly2003** [hitchao/Jvedio#326]
提一个小建议，每页的影片数量希望可以自定义，多一点像4.6那样就很好用.现在每页就固定10个影片，影片多了得不停地翻页，不太方便

**Comment by hitchao** [comment]
页码旁边可以设置

![image](https://github.com/hitchao/Jvedio/assets/23113383/0282e4dc-22aa-47f5-a78e-06058f4ca3c9)
