### ISSUE TITLE
无法下载刮削插件

### ISSUE THREAD

**Issue by wowowot** [hitchao/Jvedio#327]
- 出现问题的版本：（如5.3.1.0）
- 电脑系统：（如 win 7）

### 描述：
IP已经现在是国外,
选项网络里的www.google.com也测试成功
但是插件界面始终提示要翻墙
![微信图片_20230801173409](https://github.com/hitchao/Jvedio/assets/141132624/9cc2e2ce-9d1e-4493-9526-ef16aab4b13f)
![微信图片_20230801173409_1](https://github.com/hitchao/Jvedio/assets/141132624/deffa5b5-f7f5-4338-a01b-9bd4cc5a7d95)
![微信图片_20230801173409_2](https://github.com/hitchao/Jvedio/assets/141132624/14c1ccc7-0d98-44a5-8588-d5e1f1a68947)

**Comment by hitchao** [comment]
切换代理后重启jvedio
