### ISSUE TITLE
视频库无法显示缩略图

### ISSUE THREAD

**Issue by usally** [hitchao/Jvedio#33]
在加载完视频之后，没有显示缩略图，下方提示“当前界面0个，总计0个”，但已有视频在库中。重启和另建新库导入仍有相同问题，且一直没有正常显示

**Comment by jvedio** [comment]
把数据库发我看一下

**Comment by usally** [comment]
不确定你要的具体是哪个文件，对软件应用不熟悉。我把database打压缩在这里了

[DataBase.zip](https://github.com/hitchao/Jvedio/files/5843067/DataBase.zip)

**Comment by jvedio** [comment]
我这里显示可以的，注意一下右键是不是加了什么限制条件

**Comment by jvedio** [comment]
我这里显示可以的，注意一下右键是不是加了什么限制条件

**Comment by usally** [comment]
留意了一下确实是限定了有图影片，火星了。但这从来没被设置过，不知道是不是初始或者什么条件触发了这个设置
