### ISSUE TITLE
各处存储版本号格式不同，导致检查更新始终有新版本

### ISSUE THREAD

**Issue by kk77mgj** [hitchao/Jvedio#332]
### 描述

当前版本显示“5.3.1.0”，最新版本显示“5.3.1”，关于中的版本号显示“5.3”，小版本号都被省去了，似乎不被认为是相同版本，每次打开程序都会弹出提示更新的信息。

**Comment by TianYaDY** [comment]
同样的问题

**Comment by hitchao** [comment]
版本 [Jvedio-5.4](https://github.com/hitchao/Jvedio/releases/tag/5.4) 已修复
