### ISSUE TITLE
5.3.1在win11下无法扫描出视频文件

### ISSUE THREAD

**Issue by tjlakewalker** [hitchao/Jvedio#340]
### 反馈/建议
5.3.1在win11下无法扫描出视频文件

- 出现问题的版本：5.3.1.0
- 电脑系统：win11

### 描述：
版本5.3.1扫描文件，无法识别出文件夹下的视频文件，目前测试过mp4和mkv，都无法扫描出。

曾尝试过将视频文件拖到软件上，会生成扫描任务，但是显示如下：

总数    0       已导入    0
更新    0        未导入    0

### 日志文件：
点击扫描任务，并选择其中一个，点击结果，可以看到除视频文件外的其他文件，如srt、jpg等。

点击“查看异常”，没有任何日志。

**Comment by hitchao** [comment]
某些 dll 会被 win11 限制，找到该 dll 右键解除限制即可
