### ISSUE TITLE
5.4 版本 bus同步提示登陆到老司机论坛 哪里登陆？

### ISSUE THREAD

**Issue by YAMANAIAME112** [hitchao/Jvedio#355]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：（如5.0.0.0）
- 电脑系统：（如 win 10）
- 提出的建议：xxx

### 描述：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。

### 日志文件：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/07_Log)

**Comment by jkwtbmyz** [comment]
javbus似乎最近修改规则了 几个刮削器都出现这个问题

**Comment by kk77mgj** [comment]
好像要登录了，等插件更新吧

**Comment by baby7** [comment]
在bus插件的新增网址处，后面可以增加header，你在浏览器登录后复制header就可以了

**Comment by WallJacking** [comment]
> 可以了已解决，但是复制header的时候一定要新建一个文本文档自己手动换行，不然直接粘贴刮削器插件识别不到。
可以使用火狐访问，这样获取的header不需要自行手动调整换行
