### ISSUE TITLE
能否加入拖拽导入功能

### ISSUE THREAD

**Issue by kenz1025** [hitchao/Jvedio#36]
能否加入拖拽导入功能？？
功能设置里的启动自动扫描每次都会全盘重新扫描文件夹，很多修改网址后用jvedio刮下来的信息和自己修改过的信息都会重置，所以想关闭自动扫描，把新归档的文件拖入窗口导入，现在的单个导入每次都要选文件夹，ui里的“拖入文件至此”也没有作用

**Comment by jvedio** [comment]
这个功能已经有了，直接拖文件夹或者视频或者两者混合，拖动到主界面就行了

**Comment by jvedio** [comment]
同样的也可以拖动 nfo 或包含 nfo 的文件夹或者两者混合

**Comment by kenz1025** [comment]
感谢回复！
再次尝试拖拽还是不行，ui显示黑色圈圈加斜杠的禁行标志，文件夹，单独视频和单独nfo都尝试过了
最新版本的4.3.4.2

**Comment by hitchao** [comment]
非管理员模式启动才能拖拽
