### ISSUE TITLE
视频信息搜刮

### ISSUE THREAD

**Issue by nixinonana** [hitchao/Jvedio#37]
之前能自动搜刮视频信息，不过现在用不了，设置的同步信息自己添加了网站保存以后，再次打开还是会消失不见

**Comment by nixinonana** [comment]
请问服务器源应该怎么找，目前只有一个DB，是所有服务器源都需要cookie嘛

**Comment by hitchao** [comment]
服务器有
* bus
* Bus欧美
* Db（需要cookie）
* FC2官网

具体网址，需要自行搜索

**Comment by nixinonana** [comment]
bus和db都可以，不过fc2不行，成功通过了测试，并且保存了，重新点开以后又不可以了

**Comment by hitchao** [comment]
fc2.content 这个网址

**Comment by nixinonana** [comment]
还有一个问题是批处理的话可以自动搜刮信息，但是无法自动生成缩略图
![image](https://user-images.githubusercontent.com/63407490/108353035-923c4080-71df-11eb-8e28-a1b560ef3e51.png)
点进去的话会正常显示搜刮到的信息，但是如果想之间看到缩略图需要一个一个去右键生成。这个是正常的嘛？我记得以前可以直接生成

**Comment by hitchao** [comment]
最近搜刮好像有点问题，网站似乎加了反爬

**Comment by tjmannn** [comment]
好像有反爬
