### ISSUE TITLE
导入时复制预览图显示扩展名不支持，只能导入封面和缩略图

### ISSUE THREAD

**Issue by 18371097369** [hitchao/Jvedio#390]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：（如5.4）
- 电脑系统：（如 win 11）
- 提出的建议：建议把演员头像尺寸接触长宽比限制，改回以前的自由显示。

### 日志文件：

<img width="961" alt="搜狗截图20231220113941" src="https://github.com/hitchao/Jvedio/assets/39733846/209968d8-7161-490e-ad4b-1fbe77645f6f">
<img width="751" alt="搜狗截图20231220114001" src="https://github.com/hitchao/Jvedio/assets/39733846/29b33e15-465a-4102-b19a-1a6e57766da1">

**Comment by hitchao** [comment]
预览图目前应该不支持复制，不过可以在后续版本加入

**Comment by 18371097369** [comment]
> > **请勿上传任何暴力、色情、恐怖的信息或图片！**
> 
> ### 反馈/建议
> * 出现问题的版本：（如5.4）
> * 电脑系统：（如 win 11）
> * 提出的建议：建议把演员头像尺寸接触长宽比限制，改回以前的自由显示。
> 
> ### 描述：我是用其他软件刮削好nfo和预览图之后再导入的，之前在设置里选择复制图片，然后只要是文件名里有设置的字符的就能复制一份图片到对应文件夹，现在每次只能导入封面图和缩略图，其他都显示 未导入 扩展名不支持，我尝试了从5.0版本到5.4的所有版本都不行，之前的电脑是没问题的，很久没用了，现在换电脑了就一直这样，怎么解决谢谢。
> ### 日志文件：
> <img alt="搜狗截图20231220113941" width="961" src="https://private-user-images.githubusercontent.com/39733846/291772916-209968d8-7161-490e-ad4b-1fbe77645f6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjMyMjMsIm5iZiI6MTcwMzMyMjkyMywicGF0aCI6Ii8zOTczMzg0Ni8yOTE3NzI5MTYtMjA5OTY4ZDgtNzE2MS00OTBlLWFkNGItMWZiZTc3NjQ1ZjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDA5MTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjOWEwZTk4OWJmZGVhYzg2MzcxYTkyY2NmMjQwZjNlOTQ1NjAyMDNhN2NhMzYyNDY5OTI2YzFlMzY1NDE2YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C4NsllWOrdDi6CIX36kwyPZh2MjM3f3BR_mg2-oFmq8"> <img alt="搜狗截图20231220114001" width="751" src="https://private-user-images.githubusercontent.com/39733846/291772944-29b33e15-465a-4102-b19a-1a6e57766da1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjMyMjMsIm5iZiI6MTcwMzMyMjkyMywicGF0aCI6Ii8zOTczMzg0Ni8yOTE3NzI5NDQtMjliMzNlMTUtNDY1YS00MTAyLWIxOWEtMWE2ZTU3NzY2ZGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDA5MTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYzY0NDY5MDk0MjExNGI2YmVhNTg1YWZhYWUxMjE0NmYxM2I4ZjQyODA3NTRmMmQ2ZjdhNzQ3MGI5Mzk1YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EP-jBI4XNzUMacvdnxYamS2xc5wAsNk-NkB9uf2VDIY">

**Comment by 18371097369** [comment]
> 预览图目前应该不支持复制，不过可以在后续版本加入

我尝试了几次有意外发现，默认的设置例如填入 .screenshot 是查找文件名包含screenshot的图片然后复制，我这里不管怎么改预览图和影片截图都不会复制。
但是当我参考前面图片相对于软件路径 ./Pic 的格式，把.preview改成./extrafanart，然后就能扫描刮削好的预览图并复制到data里了。完美解决了，谢谢大大，期待下个版本更新！
<img width="520" alt="搜狗截图20231223171701" src="https://github.com/hitchao/Jvedio/assets/39733846/1e6d878b-7ec2-45dd-b253-b9e9aec3b9bd">
