### ISSUE TITLE
无法扫描外置存储设备

### ISSUE THREAD

**Issue by icyphoenix98** [hitchao/Jvedio#4]
似乎import.exe 对于外置硬盘的支持有问题，在扫描的时候会直接崩溃。
而且即使手动添加以后，javedio软件本体也无法读取，database里是有数据的。
而且本体读取的时候直接报错：

************** 异常文本 **************
System.ArgumentException: 参数“Number”的类型为“System.DBNull”，它不是数值类型。
   在 Microsoft.VisualBasic.Conversion.Int(Object Number)
   在 Javedio.Form1.ReadfromDatebase(String sql, Int32 PageNum)
   在 Javedio.Form1.SelectFromDatabase(String sql, Int32 PageNum)
   在 Javedio.Form1.Label6_Click(Object sender, EventArgs e)
   在 System.EventHandler.Invoke(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.Label.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.4075.0 built by: NET48REL1LAST
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Javedio
    程序集版本:1.1.0.0
    Win32 版本:1.1
    基本代码:file:///D:/KevinZhou/Data/%E9%97%B2%E7%BD%AE/%E3%80%902020.1.1%E3%80%91Javedio%202.0/%E3%80%902020.1.1%E3%80%91Javedio%202.0/Javedio.exe
----------------------------------------
Microsoft.VisualBasic
    程序集版本:10.0.0.0
    Win32 版本:14.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.4001.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.4075.0 built by: NET48REL1LAST
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.4042.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
MaterialSkin
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///D:/KevinZhou/Data/%E9%97%B2%E7%BD%AE/%E3%80%902020.1.1%E3%80%91Javedio%202.0/%E3%80%902020.1.1%E3%80%91Javedio%202.0/MaterialSkin.DLL
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Data.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Data.resources.dll
----------------------------------------
System.Transactions
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Microsoft.VisualBasic.resources
    程序集版本:10.0.0.0
    Win32 版本:14.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic.resources/v4.0_10.0.0.0_zh-Hans_b03f5f7f11d50a3a/Microsoft.VisualBasic.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

**Comment by hitchao** [comment]
外置硬盘是指移动硬盘吗？


 
---原始邮件---
发件人: "Icyphoenix"<notifications@github.com&gt;
发送时间: 2020年1月7日(星期二) 晚上8:21
收件人: "hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hitchao/Javedio-2.0] 无法扫描外置存储设备 (#4)



似乎import.exe 对于外置硬盘的支持有问题，在扫描的时候会直接崩溃。
 而且即使手动添加以后，javedio软件本体也无法读取，database里是有数据的。
 而且本体读取的时候直接报错：
 
************** 异常文本 **************
 System.ArgumentException: 参数“Number”的类型为“System.DBNull”，它不是数值类型。
 在 Microsoft.VisualBasic.Conversion.Int(Object Number)
 在 Javedio.Form1.ReadfromDatebase(String sql, Int32 PageNum)
 在 Javedio.Form1.SelectFromDatabase(String sql, Int32 PageNum)
 在 Javedio.Form1.Label6_Click(Object sender, EventArgs e)
 在 System.EventHandler.Invoke(Object sender, EventArgs e)
 在 System.Windows.Forms.Control.OnClick(EventArgs e)
 在 System.Windows.Forms.Control.WmMouseUp(Message&amp; m, MouseButtons button, Int32 clicks)
 在 System.Windows.Forms.Control.WndProc(Message&amp; m)
 在 System.Windows.Forms.Label.WndProc(Message&amp; m)
 在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message&amp; m)
 在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&amp; m)
 在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 
************** 已加载的程序集 **************
 mscorlib
 程序集版本:4.0.0.0
 Win32 版本:4.8.4075.0 built by: NET48REL1LAST
 基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
 
Javedio
 程序集版本:1.1.0.0
 Win32 版本:1.1
 基本代码:file:///D:/KevinZhou/Data/%E9%97%B2%E7%BD%AE/%E3%80%902020.1.1%E3%80%91Javedio%202.0/%E3%80%902020.1.1%E3%80%91Javedio%202.0/Javedio.exe
 
Microsoft.VisualBasic
 程序集版本:10.0.0.0
 Win32 版本:14.8.3752.0 built by: NET48REL1
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
 
System
 程序集版本:4.0.0.0
 Win32 版本:4.8.4001.0 built by: NET48REL1LAST_C
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
 
System.Core
 程序集版本:4.0.0.0
 Win32 版本:4.8.4075.0 built by: NET48REL1LAST
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
 
System.Windows.Forms
 程序集版本:4.0.0.0
 Win32 版本:4.8.4042.0 built by: NET48REL1LAST_C
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
 
System.Drawing
 程序集版本:4.0.0.0
 Win32 版本:4.8.3752.0 built by: NET48REL1
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
 
System.Configuration
 程序集版本:4.0.0.0
 Win32 版本:4.8.3752.0 built by: NET48REL1
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
 
System.Xml
 程序集版本:4.0.0.0
 Win32 版本:4.8.3752.0 built by: NET48REL1
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
 
System.Runtime.Remoting
 程序集版本:4.0.0.0
 Win32 版本:4.8.3752.0 built by: NET48REL1
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
 
MaterialSkin
 程序集版本:1.0.0.0
 Win32 版本:1.0.0.0
 基本代码:file:///D:/KevinZhou/Data/%E9%97%B2%E7%BD%AE/%E3%80%902020.1.1%E3%80%91Javedio%202.0/%E3%80%902020.1.1%E3%80%91Javedio%202.0/MaterialSkin.DLL
 
Accessibility
 程序集版本:4.0.0.0
 Win32 版本:4.8.3752.0 built by: NET48REL1
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
 
System.Data
 程序集版本:4.0.0.0
 Win32 版本:4.8.3752.0 built by: NET48REL1
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
 
System.Data.resources
 程序集版本:4.0.0.0
 Win32 版本:4.8.3752.0 built by: NET48REL1
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Data.resources.dll
 
System.Transactions
 程序集版本:4.0.0.0
 Win32 版本:4.8.3752.0 built by: NET48REL1
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
 
System.EnterpriseServices
 程序集版本:4.0.0.0
 Win32 版本:4.8.3752.0 built by: NET48REL1
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
 
mscorlib.resources
 程序集版本:4.0.0.0
 Win32 版本:4.8.3752.0 built by: NET48REL1
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
 
Microsoft.VisualBasic.resources
 程序集版本:10.0.0.0
 Win32 版本:14.8.3752.0 built by: NET48REL1
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic.resources/v4.0_10.0.0.0_zh-Hans_b03f5f7f11d50a3a/Microsoft.VisualBasic.resources.dll
 
System.Windows.Forms.resources
 程序集版本:4.0.0.0
 Win32 版本:4.8.3752.0 built by: NET48REL1
 基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
 
************** JIT 调试 **************
 要启用实时(JIT)调试，
 该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
 jitDebugging 值。
 编译应用程序时还必须启用
 调试。
 
例如:

**Comment by icyphoenix98** [comment]
自组的硬盘阵列，用USB3.1直连的。

**Comment by hitchao** [comment]
磁盘阵列没测试过，😂😂😂因为我没有磁盘阵列，没法测试，另外你访问磁盘阵列是通过什么方式？


 
---原始邮件---
发件人: "Icyphoenix"<notifications@github.com&gt;
发送时间: 2020年1月7日(星期二) 晚上9:38
收件人: "hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"hitchao"<2415923016@qq.com&gt;;
主题: Re: [hitchao/Javedio-2.0] 无法扫描外置存储设备 (#4)



自组的硬盘阵列，用USB3.1直连的。

**Comment by icyphoenix98** [comment]
就是直接usb插线直连，类似于直接挂载硬盘。（有种大型u盘的感觉？）

**Comment by hitchao** [comment]
地址栏是什么呢？，截个图看看


 
---原始邮件---
发件人: "Icyphoenix"<notifications@github.com&gt;
发送时间: 2020年1月7日(星期二) 晚上9:43
收件人: "hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"hitchao"<2415923016@qq.com&gt;;
主题: Re: [hitchao/Javedio-2.0] 无法扫描外置存储设备 (#4)



就是直接usb插线直连，类似于直接挂载硬盘。（有种大型u盘的感觉？）

**Comment by icyphoenix98** [comment]
![address](https://user-images.githubusercontent.com/38468147/71899752-54c15300-3197-11ea-84d1-286e7adf56e1.png)

**Comment by hitchao** [comment]
理论上应该能读的，可真是奇怪了，至于system null报错，确实普遍存在这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Icyphoenix"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月7日(星期二) 晚上9:47
收件人:&nbsp;"hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送:&nbsp;"chao"<2415923016@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [hitchao/Javedio-2.0] 无法扫描外置存储设备 (#4)

**Comment by icyphoenix98** [comment]
在手动添加的时候文件也可以识别到，但是软件本体会报错，似乎不能识别的样子，自动扫描则是直接崩溃的诡异情况了

**Comment by hitchao** [comment]
把视频复制到其他目录看看能导入吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Icyphoenix"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月7日(星期二) 晚上9:54
收件人:&nbsp;"hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送:&nbsp;"chao"<2415923016@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [hitchao/Javedio-2.0] 无法扫描外置存储设备 (#4)




在手动添加的时候文件也可以识别到，但是软件本体会报错，似乎不能识别的样子，自动扫描则是直接崩溃的诡异情况了

**Comment by icyphoenix98** [comment]
复制到pc内置的硬盘的话是没有问题，但是如果是单纯在外置存储里重建文件夹只放一个视频的话，还是一样的import崩溃，手动添加本体报错

**Comment by kingszhe9664** [comment]
最近也遇到最近的问题，外置硬盘内容 导入后，但是在列表中查不到
