### ISSUE TITLE
最近javbus同步缩略图有报错

### ISSUE THREAD

**Issue by RobertChou** [hitchao/Jvedio#40]
最近javbus同步缩略图有报错，请帮忙看看，英文的意思好像是被限制了。

**Comment by hitchao** [comment]
日志文件发一下

**Comment by RobertChou** [comment]
【2021/2/14 21:58:41】=>地址：http://hitchao.gitee.io/jvedioupdate/Version，失败原因：远程服务器返回错误: (404) 未找到。
【2021/2/14 22:05:43】=>地址：https://www.buscdn.me/JUL-465，失败原因：操作已超时。
【2021/2/14 22:06:38】=>地址：https://pics.javcdn.net/cover/82xo_b.jpg，失败原因：操作超时
【2021/2/14 22:06:39】=>地址：https://pics.javcdn.net/cover/82xn_b.jpg，失败原因：操作已超时。
【2021/2/14 22:07:48】=>地址：https://www.buscdn.me/LULU-053，失败原因：超时！
【2021/2/14 22:07:48】=>地址：https://www.buscdn.me/LULU-053，错误原因：获取网页源码失败
【2021/2/14 22:07:55】=>地址：https://pics.javcdn.pw/thumb/7hu7.jpg，失败原因：操作超时
【2021/2/14 22:08:01】=>地址：https://pics.javcdn.pw/thumb/82b0.jpg，失败原因：操作超时
【2021/2/14 22:08:32】=>地址：https://pics.javcdn.net/cover/82wq_b.jpg，失败原因：操作已超时。
【2021/2/14 22:13:35】=>地址：https://pics.dmm.co.jp/digital/video/juy00195/juy00195jp-2.jpg，失败原因：操作已超时。
【2021/2/14 22:13:49】=>URL=https://www.buscdn.me/star/na9,Message-该网址无演员信息：https://www.buscdn.me/star/na9
【2021/2/14 22:31:24】=>地址：http://hitchao.gitee.io/jvedioupdate/Version，失败原因：远程服务器返回错误: (404) 未找到。
![捕获](https://user-images.githubusercontent.com/4404703/107896753-2e611000-6f72-11eb-9891-206bbbd6adaa.PNG)

**Comment by hitchao** [comment]
已解决

**Comment by 1369411717** [comment]
> 已解决

请问一下解决办法是什么？

**Comment by hitchao** [comment]
jvedio4.5.0.0已修复，预计月底发布，内测版可加 tg 群获取

**Comment by RobertChou** [comment]
> 
> 
> jvedio4.5.0.0已修复，预计月底发布，内测版可加 tg 群获取

群号或者群链接是？

**Comment by vvvvvvning** [comment]
同求群

**Comment by hitchao** [comment]
https://t.me/Jvedio
