### ISSUE TITLE
如果我要通过爬虫插件导入演员的国家，生日等信息，应该写到哪个Key上

### ISSUE THREAD

**Issue by 1654061616** [hitchao/Jvedio#417]
我想通过爬虫写这些字段
![2](https://github.com/hitchao/Jvedio/assets/97574262/d67d1aef-c9a8-4f1b-80a9-0576659829da)

**Comment by 1654061616** [comment]
看代码好像没有这个功能？

**Comment by hitchao** [comment]
忘记了，晚上回去看看，貌似还没有接口

**Comment by 1654061616** [comment]
问题不大，我用Python抓取直接写数据库了
