### ISSUE TITLE
我遇到的问题反馈。

### ISSUE THREAD

**Issue by vvvvvvning** [hitchao/Jvedio#42]
1：标签、类别 2项同步不了。
1-2：手动增加类别无法精确增加到“主题”，“角色”，“服装”等等这些。
2：建议以下2个网站到同步信息服务器，只能增加javbus有些javbus没有。avmoo网站能通过检测，但是增加启用不了服务器（这个网站广告少感觉比javbus好很多）。
- https://avmoo.cyou/cn
- http://www.javlibrary.com/cn/
2-2：javbus同步的缩略图以及演员头像都是错误的嘿嘿的一堆字母。

另，请问有没有手机app下载可以局域网连接这个Windows软件的数据库同步，这样就好方便，电脑手机同步。

感谢，这是我用过最好的软件收藏了。感谢大大！

**Comment by hitchao** [comment]
谢谢，有空我会添加的

**Comment by bobipoppy** [comment]
![1](https://user-images.githubusercontent.com/50575997/108619168-e81e1c00-745d-11eb-82b0-b865ddb64611.png)
这个怎么解决呢？

**Comment by hitchao** [comment]
最新版已解决

**Comment by hitchao** [comment]
> 1：标签、类别 2项同步不了。
> 1-2：手动增加类别无法精确增加到“主题”，“角色”，“服装”等等这些。
> 2：建议以下2个网站到同步信息服务器，只能增加javbus有些javbus没有。avmoo网站能通过检测，但是增加启用不了服务器（这个网站广告少感觉比javbus好很多）。
> 
> * https://avmoo.cyou/cn
> * http://www.javlibrary.com/cn/
>   2-2：javbus同步的缩略图以及演员头像都是错误的嘿嘿的一堆字母。
> 
> 另，请问有没有手机app下载可以局域网连接这个Windows软件的数据库同步，这样就好方便，电脑手机同步。
> 
> 感谢，这是我用过最好的软件收藏了。感谢大大！

library已有，avmoo已添加
