### ISSUE TITLE
同步信息后类别不正常显示

### ISSUE THREAD

**Issue by gitzan** [hitchao/Jvedio#43]
同步信息后类别一栏不显示，编辑信息中添加类别后同步，添加的类别消失。
服务器源和代理可以正常使用。
![捕获](https://user-images.githubusercontent.com/79397293/108619725-a5f6d980-7461-11eb-8079-c16543a2cc4b.PNG)
![捕获2](https://user-images.githubusercontent.com/79397293/108619731-ab542400-7461-11eb-8089-d26bc93417c5.PNG)

**Comment by hitchao** [comment]
发一下识别码

**Comment by hitchao** [comment]
已修复
