### ISSUE TITLE
影片目录扫描问题

### ISSUE THREAD

**Issue by vvvvvvning** [hitchao/Jvedio#46]
影片二次扫描问题：
第一次扫描软件出来的识别码，（识别码错误，自己更改纠正错误）
第二次扫描相同的位置（之前的位置已经扫描过），又出来了那个错误的识别码，此时软件上有2个相同路径的影片识别码出现。

建议：去除相同路径下的影片新增。

**Comment by hitchao** [comment]
具体更改前后的文件名称发一下

**Comment by vvvvvvning** [comment]
第一次扫描文件软件识别：MIUM-657
修正后：300MIUM-657
重启软件
第二次扫描文件软件新增识别MIUM-657

结果软件内存在2个相同路径文件

**Comment by hitchao** [comment]
手动修改吧
