### ISSUE TITLE
影片批量同步预览图问题。

### ISSUE THREAD

**Issue by vvvvvvning** [hitchao/Jvedio#47]
在javbus服务器上没有预览图的，自己手动增加文件夹和预览图了，批量同步还是判断未同步，但是每次都用同步都显示
“同步信息成功：XXX”然后就暂停1分钟了，请问在哪里设置一下让他判断已经同步了，这样就不用每次都等了。

**Comment by hitchao** [comment]
好像没法判断，如果数据空中存储预览图的地址为空就会爬取

**Comment by vvvvvvning** [comment]
假如有100个影片，70个同步了（有预览图），30个同步了（没有预览图）（手动增加了2个文件夹和预览图，软件也能正常显示）
第二次批量同步就会出现未同步的：“30个同步了（没有预览图）”--其中2个手动增加了的还是判断为未同步。
每次批量同步都是这样，有没有办法可以增加一个设置txt目录，让软件判断那2个手动增加的已经有预览图了的，不用同步了。这样就不用每次同步都要等这30个影片同步完成后继续同步真正需要同步的影片了。

**Comment by hitchao** [comment]
已修复
