### ISSUE TITLE
4.5.1更新还是显示4.5.0

### ISSUE THREAD

**Issue by RobertChou** [hitchao/Jvedio#49]
4.5.0检查更新下载后还是显示4.5.0，不是4.5.1，请看一下。

**Comment by hitchao** [comment]
多更新几次，可能是更新文件没下载全

**Comment by RobertChou** [comment]
> 
> 
> 多更新几次，可能是更新文件没下载全

github上的release链接没有4.5.1的程序包

**Comment by RobertChou** [comment]
> 
> 
> 多更新几次，可能是更新文件没下载全

更新了好几次，还是没有更新成功。

**Comment by hitchao** [comment]
https://github.com/hitchao/Jvedio/releases/tag/Jvedio4.5.1.0

**Comment by RobertChou** [comment]
> 
> 
> https://github.com/hitchao/Jvedio/releases/tag/Jvedio4.5.1.0

只有两个source code的压缩包，应该还有一个程序包吧？像这样的 Jvedio4.5.0.0.zip

**Comment by hitchao** [comment]
添加了

**Comment by RobertChou** [comment]
> 
> 
> 添加了

谢谢，已更新，问一下新的功能：加载演员出演过的其他作品，这个如何使用啊？入口在哪？

**Comment by hitchao** [comment]
智能分类，点击演员

**Comment by RobertChou** [comment]
> 
> 
> 智能分类，点击演员

点击了演员，右键 “显示剩余影片”，没什么反应。

**Comment by hitchao** [comment]
点击演员后，演员那里有一个黄色的按钮
