### ISSUE TITLE
视频类型

### ISSUE THREAD

**Issue by wujie985432** [hitchao/Jvedio#51]
![image](https://user-images.githubusercontent.com/80050604/110593029-fd14e200-81b5-11eb-9cdd-492374d9af30.png)
![image](https://user-images.githubusercontent.com/80050604/110593076-11f17580-81b6-11eb-8941-9efa3b9f81d3.png)
老版本里面扫描后自动分类视频类型而新版本里就没有，希望可以添加进去

**Comment by hitchao** [comment]
右键-视频类型-即可筛选
