### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by wujie985432** [hitchao/Jvedio#55]
![image](https://user-images.githubusercontent.com/80050604/111297022-1e7b3f80-8688-11eb-96f7-e074b3e46a20.png)
现在的版本都不能自动更新，每次更新就会崩溃
还希望可以像以前版本一样可以在线更新不然每次下新版本后所有的设置都要重新选，而且更新后日志可以显示更新了什么内容

**Comment by hitchao** [comment]
目前是支持在线更新的

**Comment by wujie985432** [comment]
![image](https://user-images.githubusercontent.com/80050604/111612554-8bbdda80-8818-11eb-804d-975d5a3eb8e4.png)


> 目前是支持在线更新的

![image](https://user-images.githubusercontent.com/80050604/111612646-a1cb9b00-8818-11eb-9b1c-b47cbbe5c05b.png)

那我每次点更新就会崩溃是什么情况呢？
