### ISSUE TITLE
还是欧美刮削问题

### ISSUE THREAD

**Issue by wujie985432** [hitchao/Jvedio#56]
![image](https://user-images.githubusercontent.com/80050604/111302057-e37c0a80-868d-11eb-881f-e4d5a02c69f2.png)
从bd刮削无码和有码都可以，就是不能刮削欧美的信息和图片

**Comment by hitchao** [comment]
欧美目前暂时支持bus的，还不支持 db

**Comment by wujie985432** [comment]
用bus刮削也不行 欧美的信息不显示

**Comment by wujie985432** [comment]
> 欧美目前暂时支持bus的，还不支持 db

![image](https://user-images.githubusercontent.com/80050604/111613213-3c2bde80-8819-11eb-8f4a-8e6de10394b0.png)
我发现用默认的库名就可以刮削，如果改名的话就刮削不了
