### ISSUE TITLE
网址无法连接，停止下载

### ISSUE THREAD

**Issue by lenswt** [hitchao/Jvedio#6]
已经全局翻墙，请问一下相关设置

**Comment by hitchao** [comment]
加我扣3150659291讨论吧~


 
---原始邮件---
发件人: "lenswt"<notifications@github.com&gt;
发送时间: 2020年1月12日(星期日) 上午10:42
收件人: "hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hitchao/Javedio-2.0] 网址无法连接，停止下载 (#6)



已经全局翻墙，请问一下相关设置

**Comment by Bu-Chuan** [comment]
换个网址就行了

**Comment by FFFTQ** [comment]
试试这个，还可以  https://mayi.lanshuapi.com/aff/TzaX
