### ISSUE TITLE
服务器有

### ISSUE THREAD

**Issue by for-pyja** [hitchao/Jvedio#60]
服务器有
* bus
* Bus欧美
* Db（需要cookie）
* FC2官网

具体网址，需要自行搜索

_Originally posted by @hitchao in https://github.com/hitchao/Jvedio/issues/37#issuecomment-781257804_

**Comment by for-pyja** [comment]
https://hpjav.tv/资源很广，而且不用代理，我用idm下载能达到30M/s
https://www.netflav.com/ 和hpjav差不多，但是要代理
老哥可以考虑爬下

**Comment by hitchao** [comment]
可以，等以后可以加上
