### ISSUE TITLE
可否将下载的图片保存在影片各自的文件夹中

### ISSUE THREAD

**Issue by sarsbigodg** [hitchao/Jvedio#63]
大大软件很好用，但下载的图片都集中保存在一个地方，这样无法用KODI，可否能把图片保存在各自的文件夹里呢

**Comment by hitchao** [comment]
也可以，不过得等一段时间了，最近没什么时间更新了

**Comment by a3744** [comment]
赞同，感觉这个软件可以当成刮削器来用，可以直接刮NAS上的电影，图片放在一个文件夹就可以直接导入jellyfin了。

**Comment by jesus-liu** [comment]
大佬，javbus的网址是什么 做系统收藏的网站全没了 或者其他的网站也行

**Comment by a3744** [comment]
https://www.fanbus.bar&nbsp;


??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月15日(星期二) 凌晨1:36
收件人: ***@***.***&gt;; 
抄送: "‭    ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hitchao/Jvedio] 可否将下载的图片保存在影片各自的文件夹中 (#63)





 
大佬，javbus的网址是什么 做系统收藏的网站全没了 或者其他的网站也行
