### ISSUE TITLE
应用升级时如果原来安装目录带有空格等字符时导致安装失败

### ISSUE THREAD

**Issue by iamdamaha** [hitchao/Jvedio#65]
看了一下下载后自动升级的批处理，如果遇到安装目录是这种形式C:\Program Files\Jvedio，需要加上引号才能执行。可以考虑把拷贝目标目录都加上引号兼容其他目录名称。
xcopy /y/e \TEMP "C:\Program Files\Jvedio"  & TIMEOUT /T 1 & exit

**Comment by hitchao** [comment]
按理说应该不会的，因为都是同目录下复制

**Comment by hitchao** [comment]
修复了
