### ISSUE TITLE
现在影片详细页，除了点女优名字外，点其他选项全部失效。

### ISSUE THREAD

**Issue by xiwensong** [hitchao/Jvedio#66]
或许我在标题表达的不清楚，详细点说，就是在某一影片详细页，只有点女优名字出来的筛选结果才是正确的，其他不论是点导演、制作商、发行商、系列名、类别等，出来的结果都是全部的影片，而不是筛选过的结果。

**Comment by xiwensong** [comment]
还有点开“我的清单”，里面什么都看不到。哎，真不知道怎么滚回上一个版本。目前这个版本bug太多了

**Comment by xiwensong** [comment]
我重新下载了4.5.1.0版，上述两个问题全没有了，太好了！

**Comment by hitchao** [comment]
这个版本确实有点 Bug

**Comment by hitchao** [comment]
修复了
