### ISSUE TITLE
还是升级问题

### ISSUE THREAD

**Issue by wujie985432** [hitchao/Jvedio#69]
![image](https://user-images.githubusercontent.com/80050604/113506231-26871a80-9576-11eb-8d02-f8fba39df338.png)
下了最新的4.5.6.0然后在线更新崩溃，我以为是最高版本不能更新又下了上一个版本更新再崩溃，然后看了更新源又以为要梯子才能更新再再崩溃，所以这个还是软件bug，希望可以修复
PS：不管哪个版本点检查更新不管有不有梯子都没反应，以前版本可以用，估计也bug，也希望可以修复
![image](https://user-images.githubusercontent.com/80050604/113506430-774b4300-9577-11eb-8ea7-1b4f0b1f601c.png)

**Comment by hitchao** [comment]
做了报错处理，下次有问题就会报错了，如果在线更新失败，就在官网下载压缩包解压覆盖即可
