### ISSUE TITLE
为什么同一个视频文件会重复出现一次，

### ISSUE THREAD

**Issue by feelingfrance** [hitchao/Jvedio#7]
同一个视频文件数据库里重复出现同一番号，导致主页面显示两个一样的内容，但是对应的是同一个文件，怎么解决

**Comment by hitchao** [comment]
在操作，数据库操作里，点击删除重复番号即可


 
---原始邮件---
发件人: "feelingfrance"<notifications@github.com&gt;
发送时间: 2020年1月29日(星期三) 晚上6:46
收件人: "hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hitchao/Javedio-2.0] 为什么同一个视频文件会重复出现一次， (#7)



同一个视频文件数据库里重复出现同一番号，导致主页面显示两个一样的内容，但是对应的是同一个文件，怎么解决
