### ISSUE TITLE
欧美信息刮削

### ISSUE THREAD

**Issue by wujie985432** [hitchao/Jvedio#70]
欧美用bus刮削，新版4.5.6.0下载后还是不能把信息刮削下来，又换以前的版本刮削也不能把信息下下来，图片还是以前保存下来的 无码有码都可以刮削信息就是欧美的不行 还是希望能修复一下

PS：1 能不能加一个去重复的选项， 2 多选模式里加个shift键能多选，因为一个一个的点有点麻烦

![0TLTWEUWG@AE5LU7WGGC1LS](https://user-images.githubusercontent.com/80050604/113514427-12a4de00-95a1-11eb-9dd5-0f6e49924980.png)

![L$Y`R(LODR0}GL3ODD1YOZS](https://user-images.githubusercontent.com/80050604/113514446-4aac2100-95a1-11eb-9103-e10b98744d48.png)

**Comment by hitchao** [comment]
你的欧美库私发我 qq 一份

**Comment by wujie985432** [comment]
qq号码是多少



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月5日(星期一) 下午5:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hitchao/Jvedio] 欧美信息刮削 (#70)





 
你的欧美库私发我 qq 一份

**Comment by wujie985432** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hitchao/Jvedio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月5日(星期一) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hitchao/Jvedio] 欧美信息刮削 (#70)





 
你的欧美库私发我 qq 一份

**Comment by hitchao** [comment]
3150659291

**Comment by hitchao** [comment]
已修复
