### ISSUE TITLE
扫描大磁盘崩溃

### ISSUE THREAD

**Issue by li986390329** [hitchao/Jvedio#75]
- 版本：4.5.6.0

- 类型：BUG

# 描述：

复现概率： 必现
复现步骤：选项->视频扫描->选择H盘->执行, 程序下方进度开始转圈->5s左右程序崩溃，数据库信息清零
如果设置H盘为`启动扫描目录`，则启动必然崩溃

备注：
如果设置单个小文件夹是可以扫描成功的
测试了一下，从4.5.0.0版本开始出现的，4.3.4.2是可以正常扫描的，4.5以后扫描必崩

H盘视频数量：1322
未识别视频个数：327

**Comment by hitchao** [comment]
我自己测试并未出现闪退
