### ISSUE TITLE
希望能对星级排序，打分太麻烦觉得那个收藏星级就挺好，希望能自己增加识别的分类，比如识别国产的，我在视频前加国产两个字就行

### ISSUE THREAD

**Issue by bufanchedelaosiji** [hitchao/Jvedio#76]
- 版本：4.5.0.0

- 类型：BUG/建议/其他

# 描述：

详细说明前因后果、操作步骤：如，当我点“所有视频”去浏览作品时，我点开某个作品的详情页，这个时候我再点演员，会转到这个演员所有的作品目录，然后我没办法返回到原来的浏览进度了，这个可以做一个优化吗？

# 日志文件：
请将对应的日志复制到此处，无则可不填

日志文件位于软件目录下的 Log 文件夹，具体介绍请看  https://github.com/hitchao/Jvedio/wiki/Introduction_3

**Comment by bufanchedelaosiji** [comment]
作者大大加油，之前有一家javedio也黄了，只有您了

**Comment by jvedio** [comment]
点击特别收藏就能对星级排序了，另外javedio项目我也舍弃了，因为有敏感词



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月14日(周三) 中午11:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [hitchao/Jvedio] 希望能对星级排序，打分太麻烦觉得那个收藏星级就挺好，希望能自己增加识别的分类，比如识别国产的，我在视频前加国产两个字就行 (#76)




 
作者大大加油，之前有一家javedio也黄了，只有您了

**Comment by bufanchedelaosiji** [comment]
好嘞好嘞，对了，还希望批处理里面增加一个去重的功能0v0，下的太多了有些都不知道已经重复了，扫描后才知道

> 点击特别收藏可以对星级排序了，另外javedio项目我也舍弃了，因为有敏感词
> […](#)
> ---原始邮件---发件人：***@***.***> 发送时间：2021年4月14日（周三）中午11:57收件人：***@***.***> ;; 抄送：***@***.***> ;; 主题：回复：[hitchao / Jvedio]希望能对星级排序，打分太麻烦觉得那个收藏明星就挺好，希望能自己增加识别的分类，识别识别国产的，我在视频前加国产两个字就行（[＃76](https://github.com/hitchao/Jvedio/issues/76)）作者大大加油，之前有一家javedio也黄了，只有您了 直接回复此电子邮件，在GitHub上查看或取消订阅。
