### ISSUE TITLE
一点同步信息就闪退

### ISSUE THREAD

**Issue by a3500976** [hitchao/Jvedio#77]
- 版本：4.5.6.0

- 类型：BUG

# 描述：

一点同步信息就闪退，点设置里的网址测试按钮也闪退，网络连接没有问题，浏览器可以正常进的

**Comment by xiwensong** [comment]
我也是

**Comment by hitchao** [comment]
已修复，最新版本 [Jvedio 4.6.0.1](https://github.com/hitchao/Jvedio/releases/tag/Jvedio4.6.0.1)
