### ISSUE TITLE
一点小建议和疑惑

### ISSUE THREAD

**Issue by Bouncysig18** [hitchao/Jvedio#8]
1. 我下载的番号文件中，视频文件被切分为了2个甚至更多的部分，但是使用您的文件用因为抓取同样的番号名字最后识别为重复文件，但是我认为识别重复文件是很重要不能删除的功能，所以我建议导入过程中在错误界面中的重复文件选项可以让用户自己选择是否加入数据库中，默认不加入。
2. 我在使用软件的过程中，由于重复导入了同一个文件2次（文件位置发生了变化），然后我发现对此文件设置的一系列的信息被清空还原了（喜爱程度，自己添加的自定义分类lable...）
3. 我建议自定义项可以批量添加影片，但是现在我知道的办法是对每一个影片依次添加对应的自定义分类lable
4. 我不是很明白大图和小图有什么现实的区别？
5. 建议学习javtunes，它可以做到软件内访问论坛，并在其页面看到这部影片是否下载了（这个功能我觉得是个亮点，但没有也无所谓），但javtune他这个软件内访问论坛不能搜索，一点搜索了会弹出另一个网页，但那个网页上不能显示这个影片是否下载了，所以其实这个功能在其软件上还是优点鸡肋的

**Comment by jvedio** [comment]
已经添加建议了，感谢！
