### ISSUE TITLE
视频类型失效

### ISSUE THREAD

**Issue by henryzhg** [hitchao/Jvedio#81]
- 版本：4.6.0.0

- 类型：BUG

# 描述：

前一版本视频类型可以有效筛选，但4.6.0.0版本视频类型无法正常使用
# 日志文件：
请将对应的日志复制到此处，无则可不填

日志文件位于软件目录下的 Log 文件夹，具体介绍请看  https://github.com/hitchao/Jvedio/wiki/Introduction_3

**Comment by hitchao** [comment]
并未出现这个问题
