### ISSUE TITLE
系统同步崩溃bug

### ISSUE THREAD

**Issue by whatnamewehave** [hitchao/Jvedio#82]
4.6.0.0
bug
同步信息系统崩溃bug
同步bug出现在批处理及普通同步中
bus可以正常同步
db系列同步就会崩溃，其余未尝试

**Comment by hitchao** [comment]
已修复，最新版本 [Jvedio 4.6.0.1](https://github.com/hitchao/Jvedio/releases/tag/Jvedio4.6.0.1)
