### ISSUE TITLE
添加某sox网站界面UI有问题&元数据nfo导入有BUG

### ISSUE THREAD

**Issue by kinver** [hitchao/Jvedio#83]
- 出现问题的版本：（如4.5.0.0）
4.6.0.0 

- 电脑系统：（如 win 10）
Windows 10 专业版 20H2 19042.928

# 描述：
添加某sox网站后因其服务器名称过长导致同步信息界面无法完整显示
![20210502140638](https://user-images.githubusercontent.com/33085738/116804251-f53b4380-ab4f-11eb-96c6-30a830dbcd5f.png)

工具里的元数据nfo导入的扫描文件夹选项无论选择什么文件夹都只会定位到jvedio软件的当前文件夹
![20210504222934](https://user-images.githubusercontent.com/33085738/117019767-50c02980-ad28-11eb-9ef9-9935111dd37c.png)

**Comment by kinver** [comment]
通过拖拽文件夹入虚线框的方式可以避免第二种情况发生

**Comment by hitchao** [comment]
目前不支持 sox ，文件夹问题已解决
