### ISSUE TITLE
只有我的gif无法显示么？无任何图像

### ISSUE THREAD

**Issue by xiay1113** [hitchao/Jvedio#85]
可以创建
在Jvedio\Pic\Gif
里面也可以看到可以使用
但是就是显示不出来
如果单个文件创建GIF那么立马可以显示。但是在此打开或者到别的库在回来又无法显示

**Comment by xiay1113** [comment]
4.5.1可以显示。。。。
4.6.0不能显示
GIF

**Comment by hitchao** [comment]
已修复
