### ISSUE TITLE
同步直接程序崩溃，影响使用

### ISSUE THREAD

**Issue by RobertChou** [hitchao/Jvedio#87]
# 由于一些个人原因，Jvedio 暂时维护，目前最新版 [4.6.0.0]( https://github.com/hitchao/Jvedio/releases/tag/Jvedio4.6.0.0)，或下载 [其他版本](https://github.com/hitchao/Jvedio/releases)

## 你仍然可以提交的问题，但可能在半年后才能解决，可以下载 [其他版本](https://github.com/hitchao/Jvedio/releases)

# 反馈

- 出现问题的版本：（如4.5.0.0）

- 电脑系统：（如 win 10）

# 描述：

详细说明前因后果、操作步骤。

# 日志文件：
请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/Introduction_3)

【2021/5/27 21:47:55】=> 服务器地址：https://pics.javcdn.net/thumb/88wx.jpg， 原因：远程服务器返回错误: (404) 未找到。

应该是图片没找到

**Comment by hitchao** [comment]
已修复，最新版本 [Jvedio 4.6.0.1](https://github.com/hitchao/Jvedio/releases/tag/Jvedio4.6.0.1)
