### ISSUE TITLE
同步导致程序崩溃

### ISSUE THREAD

**Issue by tjmannn** [hitchao/Jvedio#89]
# 由于一些个人原因，Jvedio 暂时维护，目前最新版 [4.6.0.0]( https://github.com/hitchao/Jvedio/releases/tag/Jvedio4.6.0.0)，或下载 [其他版本](https://github.com/hitchao/Jvedio/releases)

## 你仍然可以提交的问题，但可能在半年后才能解决，可以下载 [其他版本](https://github.com/hitchao/Jvedio/releases)

# 反馈

- 出现问题的版本：4.6.0.0，试了再上一个版本，也是同步不了

- 电脑系统： win 10

# 描述：任何同步方式都会在几秒种后导致程序崩溃关闭，比如高级同步、普通同步、页面上的地球标志同步等。同步开始的几秒钟是有流量产生的，然后就会崩溃。建立新的视频库也是同样的问题

详细说明前因后果、操作步骤。

# 日志文件：
请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/Introduction_3)

**Comment by tjmannn** [comment]
# log文件

-----【2021/6/6 12:59:54】-----
Message=>Drive returned invalid root handle
StackTrace=>
    文件: D:\Jvedio\Jvedio\Utils\FileProcess\Scan.cs 方法: ScanAllDrives 行数: 112

-----【2021/6/6 12:59:56】-----
Message=>Drive returned invalid root handle
StackTrace=>
    文件: D:\Jvedio\Jvedio\Utils\FileProcess\Scan.cs 方法: ScanAllDrives 行数: 112

-----【2021/6/6 12:59:57】-----
Message=>Drive returned invalid root handle
StackTrace=>
    文件: D:\Jvedio\Jvedio\Utils\FileProcess\Scan.cs 方法: ScanAllDrives 行数: 112

这个D盘的路径我发现并不存在

**Comment by hitchao** [comment]
已修复，最新版本 [Jvedio 4.6.0.1](https://github.com/hitchao/Jvedio/releases/tag/Jvedio4.6.0.1)
