### ISSUE TITLE
如果能增加一个按演员分类就好了

### ISSUE THREAD

**Issue by nbyh** [hitchao/Jvedio#9]
如果能增加一个按演员分类就好了

**Comment by hitchao** [comment]
你有什么分类的想法吗


 
---原始邮件---
发件人: "Hao"<notifications@github.com&gt;
发送时间: 2020年2月3日(星期一) 晚上10:11
收件人: "hitchao/Javedio-2.0"<Javedio-2.0@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hitchao/Javedio-2.0] 如果能增加一个按演员分类就好了 (#9)



如果能增加一个按演员分类就好了
