### ISSUE TITLE
WIN10指定播放器播放不起作用，还是会默认启动系统播放器

### ISSUE THREAD

**Issue by jiaosao** [hitchao/Jvedio#90]
# 由于一些个人原因，Jvedio 暂时维护，目前最新版 [4.6.0.0]( https://github.com/hitchao/Jvedio/releases/tag/Jvedio4.6.0.0)，或下载 [其他版本](https://github.com/hitchao/Jvedio/releases)

## 你仍然可以提交的问题，但可能在半年后才能解决，可以下载 [其他版本](https://github.com/hitchao/Jvedio/releases)

# 反馈
WIN10指定播放器播放不起作用，还是会默认启动系统播放器

# 描述：

详细说明前因后果、操作步骤。

# 日志文件：
请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/Introduction_3)

**Comment by hitchao** [comment]
已修复
