### ISSUE TITLE
同一部影片，既有原版无字幕版，又有中文字幕版，如何管理

### ISSUE THREAD

**Issue by zbintop** [hitchao/Jvedio#94]
同一部影片，既有原版无字幕版，又有中文字幕版，只能识别出来一个，影片一多就不知道哪部有字幕了，怎么办啊

**Comment by YaoYouGuan** [comment]
可以在番号后带-C增加中文标识，你打开Jvedio看到他就知道是有中文字幕；
再把两个播放文件命名成XX-C-1，XX-C-2，修改Jvedio中这个作品的分段视频为这两个。

我不确定Jvedio能否识别-C-1，你可以备份后，这样子试一下。

**Comment by zbintop** [comment]
感谢回复，我明白你的意思，我也是这么做的。但有一个问题，比如原版高清是无字幕的命名为XXX-001，中文字幕的是普清命名为XXX-001_C，但是导入后只有高清标签，没有中文字幕标签。我这样的影片很多，一多的话就不知道哪部有中文版本了。

**Comment by YaoYouGuan** [comment]
你的文件命名是对的吗？
1.你试着把高清无字幕的文件命名为：XXX-001-C-1，然后把这个文件设置这个作品的默认播放文件。（你说的导入后没有中字，是不是因为默认的播放文件不是带-C的）
2.把中文字幕的是普清命名为：XXX-001-C-2，然后设置分段视频为这两个文件。
3.我突然想到，分段视频不一样要同一个番号作为前缀，只要分段视频那一栏中有两个路径，就可以了。不知道是不是这样。（如果Jvedio不能识别-C-1，那就可以这样试一下）

**Comment by zbintop** [comment]
哈哈，是我理解错了，你这个方法可以。把高清无字幕的命名为XXX-001_C_1，普清有字幕的命名为XXX-001_C_2，这样确实既显示高清标签也显示中文标签。可以识别，算是目前的折中方法了，不知道以后作者会不会更新更好的方法。

**Comment by YaoYouGuan** [comment]
另外，字幕文件可以上98tang搜搜看，没准有哦，这样就可以看高清字幕资源了。

**Comment by hitchao** [comment]
文件名存在如下则显示【流出标签】："流出", "留出", "泄露", "泄密", "曝光", "flowout"；
文件名存在如下则显示【中字标签】："中字", "中文字幕", "字幕", "中文", "translated", "translate", “-C”,"_C"
文件名存在如下则显示【高清标签】："hd", "high_definition", "high definition", "高清", "2K", "4K", "8K", "16K", "32K"

**Comment by hitchao** [comment]
或者直接在标签里面添加上述也可显示

**Comment by hitchao** [comment]
分段视频规则如下：

- XXX-001-1, XXX-001-2, XXX-001-3
- XXX-001_1, XXX-001_2, XXX-001_3
- XXX-001cd1, XXX-001cd2, XXX-001cd3
- XXX-001fhd1, XXX-001fhd2, XXX-001fhd3
- XXX-001A, XXX-001B, XXX-001C

**Comment by YaoYouGuan** [comment]
👌

**Comment by jywyf** [comment]
> 分段视频规则如下：
> 
> * XXX-001-1, XXX-001-2, XXX-001-3
> * XXX-001_1, XXX-001_2, XXX-001_3
> * XXX-001cd1, XXX-001cd2, XXX-001cd3
> * XXX-001fhd1, XXX-001fhd2, XXX-001fhd3
> * XXX-001A, XXX-001B, XXX-001C

按这个改了半天，以为没有成功，因为所有视频中没有显示，后来点开详情点播放按钮看到的分段提示，希望下个版本 
1、能把本番号的分段铺开显示，点开直接播放
2、详情页添加本演员其它（本地）已添加视频
