### ISSUE TITLE
db9不能获取有效cookie，有什么方法吗？

### ISSUE THREAD

**Issue by loriple** [hitchao/Jvedio#96]
尝试过不少获取db9 cookie的方法，但都不能成功，4.6.1.1说明解决了一些db的问题，但还是不能将db9成功增加到同步中，求有效解决方法

**Comment by yy34587922** [comment]
同求，根本没法同步信息

**Comment by hitchao** [comment]
按照 [获取Cookie](https://github.com/hitchao/Jvedio/wiki/HowToGetCookies) 进行操作，目前是可以的

**Comment by loriple** [comment]
> 按照 [获取Cookie](https://github.com/hitchao/Jvedio/wiki/HowToGetCookies) 进行操作，目前是可以的
测试了，依然是获得“theme=auto; locale=zh;……”开头的词缀，在软件中不能完成测试

**Comment by loriple** [comment]
> 按照 [获取Cookie](https://github.com/hitchao/Jvedio/wiki/HowToGetCookies) 进行操作，目前是可以的

特意下载了360极速浏览器，获得的词缀依然不能通过检测

**Comment by zsw33333** [comment]
我按照 获取Cookie 进行的操作，可以同步
