### ISSUE TITLE
建议增加功能可以记忆上次扫描的路径，避免每次扫描前都要一个一个找路径添加

### ISSUE THREAD

**Issue by tjmannn** [hitchao/Jvedio#97]
# 小建议：建议增加功能可以记忆上次扫描的路径，避免每次扫描前都要一个一个找路径添加
# 由于一些个人原因，Jvedio 暂时维护，目前最新版 [4.6.0.0]( https://github.com/hitchao/Jvedio/releases/tag/Jvedio4.6.0.0)，或下载 [其他版本](https://github.com/hitchao/Jvedio/releases)

## 你仍然可以提交的问题，但可能在半年后才能解决，可以下载 [其他版本](https://github.com/hitchao/Jvedio/releases)

# 反馈

- 出现问题的版本：（如4.5.0.0）

- 电脑系统：（如 win 10）

# 描述：

详细说明前因后果、操作步骤。

# 日志文件：
请将对应的日志复制到此处，无则可不填，关于日志请看 [日志文件](https://github.com/hitchao/Jvedio/wiki/Introduction_3)

**Comment by nick1987xt** [comment]
可以在选项中添加扫描路径

**Comment by tjmannn** [comment]
我说的是 工具-视频扫描 这里

**Comment by hitchao** [comment]
5.0 已修复
