### ISSUE TITLE
影视库问题

### ISSUE THREAD

**Issue by nick1987xt** [hitchao/Jvedio#98]
影视库选项中 删除不存在的影片 和 删除不位于。。。。的影片 这几个功能都无法使用 ，点击了没有效果，在4.5之前还是可以用的，升级了4.6之后就不行了，请问大佬这该怎么办

**Comment by yizsy928** [comment]
如果更换电脑，这个资源怎么迁移到新的电脑？

**Comment by spartawhy117** [comment]
> 如果更换电脑，这个资源怎么迁移到新的电脑？

你找到方法了，我是移动硬盘，换了电脑后盘符发生变化后就找不到了，是要重新扫描还是扫描nfo信息？

**Comment by hitchao** [comment]
重新扫描即可，或者复制database目录下的的文件

**Comment by spartawhy117** [comment]
> 重新扫描即可，或者复制database目录下的的文件

我描述不够清晰，现在软件是直接复制到新电脑上了，然后插上移动硬盘，盘符和之前的不一样，影片和nfo信息都在移动硬盘了，然后打开软件，库信息还在，但是点击单个影片就告诉找不到对应的位置了。现在的操作就是把移动硬盘里的目录再次拖入到影视库里就行了？会自动扫描到nfo文件？我在工具了点了扫描nfo文件目录，还是有部分电影没有定位到新的盘符上

**Comment by hitchao** [comment]
如果移动了影片，把移动后的影片重新拖入扫描即可

**Comment by hitchao** [comment]
5.0 已可以使用
