### ISSUE TITLE
DB不能通过测试啊

### ISSUE THREAD

**Issue by ym52000000** [hitchao/Jvedio#99]
cookie填入以后依然不能通过测试，目前MOO 和321之类的也用不了  现在能用的只有BUS和FC2

**Comment by YaoYouGuan** [comment]
db30这个备用网址的cookie测试通过，你可以直接在同步信息那边，修改db的服务器地址为db30。
db的刮削就是这个情况，主站一直就用不了，要用备用的服务器网址，之前是db9，现在是db30，db主页头顶就可以看到。

**Comment by RainwalkerDean** [comment]
> db30这个备用网址的cookie测试通过，你可以直接在同步信息那边，修改db的服务器地址为db30。
> db的刮削就是这个情况，主站一直就用不了，要用备用的服务器网址，之前是db9，现在是db30，db主页头顶就可以看到。

直接改地址，cookie还要重新获取吗

**Comment by YaoYouGuan** [comment]
> > db30这个备用网址的cookie测试通过，你可以直接在同步信息那边，修改db的服务器地址为db30。
> > db的刮削就是这个情况，主站一直就用不了，要用备用的服务器网址，之前是db9，现在是db30，db主页头顶就可以看到。
> 
> 直接改地址，cookie还要重新获取吗

我刚刚试了，要重新获取cookie。原本通过的cookie，改了网址就不能通过了。

**Comment by XIANG-z25** [comment]
大佬，db现在是完全不能刮削了吗，bus缺了不少番号，db36之类的新网址重新获取cookie怎么测试都不过

**Comment by YaoYouGuan** [comment]
![360截图20220213131126143](https://user-images.githubusercontent.com/17904095/153739666-4ee03197-adaa-420e-a873-dcdf6bd45c07.jpg)

db33可以诶，360极速浏览器、谷歌浏览器都行。

**Comment by YaoYouGuan** [comment]
> 大佬，db现在是完全不能刮削了吗，bus缺了不少番号，db36之类的新网址重新获取cookie怎么测试都不过

.

**Comment by XIANG-z25** [comment]
> ![360截图20220213131126143](https://user-images.githubusercontent.com/17904095/153739666-4ee03197-adaa-420e-a873-dcdf6bd45c07.jpg)
> 
> db33可以诶，360极速浏览器、谷歌浏览器都行。

多谢，我用的edge获取的，我换个浏览器试试

**Comment by XIANG-z25** [comment]
> ![360截图20220213131126143](https://user-images.githubusercontent.com/17904095/153739666-4ee03197-adaa-420e-a873-dcdf6bd45c07.jpg)
> 
> db33可以诶，360极速浏览器、谷歌浏览器都行。

已成功，谢谢，是网站的问题，有的不行，试33立马就可以了
